// The implementation-content library on disk, as the registry holds it. Node only:
// the compiler (scripts/compile-implementation-content.mjs --registry) writes the
// registry through it and the tests compare the registry with it; the product
// imports only the registry.
//
// A package is registered when it describes a step the Plan draws as a content
// step (docs/design/content.json `steps`, reached as stepTitle.ts
// contentStepForPackage reaches it), whatever else it describes. Every part of it
// the runtime cannot project safely is withheld (protocol.ts withholdInvalid); the
// package files are never edited.
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { contentStepForPackage } from '../stepTitle.ts'
import { compileLibraryPackage } from './protocol.ts'
import type { CompiledPackage } from './protocol.ts'
import { driftOf } from './drift.ts'
import type { Drift } from './drift.ts'
import { PINNED } from '../../baseline/pinned.ts'

export const LIBRARY_ROOT = 'docs/implementation-content'

/** `drift`: the package reviewed against the pin this build carries, member by member (drift.ts). */
export type LibraryPackage = { dir: string; stepId: string; pkg: CompiledPackage; withheld: string[]; drift: Drift }

/** Every package folder under the root (a folder holding META.json), in path order; a package may sit one folder deeper than its name. */
export function packageDirs(root: string = LIBRARY_ROOT): string[] {
  const out: string[] = []
  const walk = (dir: string, depth: number): void => {
    if (existsSync(join(dir, 'META.json'))) {
      out.push(dir)
      return
    }
    if (depth >= 3) return
    for (const e of readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) if (e.isDirectory()) walk(join(dir, e.name), depth + 1)
  }
  walk(root, 0)
  return out
}

/** The library compiled: the packages the Plan registers, by step id, and the ones that describe no content step. */
export function compileLibrary(root: string = LIBRARY_ROOT): { registered: LibraryPackage[]; notSteps: LibraryPackage[] } {
  const registered: LibraryPackage[] = []
  const notSteps: LibraryPackage[] = []
  for (const dir of packageDirs(root)) {
    const metaJson = readFileSync(join(dir, 'META.json'), 'utf8')
    const contentFile = (JSON.parse(metaJson) as { contentFile?: string }).contentFile ?? 'CONTENT.md'
    const { pkg, withheld } = compileLibraryPackage(metaJson, readFileSync(join(dir, contentFile), 'utf8'))
    const content = contentStepForPackage(pkg.meta.stepId)
    // The members its step implements are the pinned policies its content step's goals map to.
    const authority = pkg.meta.baselineAuthority
    const goals = content ? [content.id, ...((content as { mergesGoals?: string[] }).mergesGoals ?? [])] : []
    const drift = driftOf(authority?.reviewedMembers as Record<string, string> | undefined, typeof authority?.pinCommit === 'string' ? authority.pinCommit : null, goals, PINNED)
    const entry = { dir: dir.replaceAll('\\', '/'), stepId: pkg.meta.stepId, pkg, withheld, drift }
    if (!content) {
      notSteps.push(entry)
      continue
    }
    const twin = registered.find((r) => contentStepForPackage(r.stepId)?.id === content.id)
    if (twin) throw new Error(`two packages for content step ${content.id}: ${twin.stepId}, ${entry.stepId}`)
    registered.push(entry)
  }
  const byId = (a: LibraryPackage, b: LibraryPackage): number => a.stepId.localeCompare(b.stepId)
  return { registered: registered.sort(byId), notSteps: notSteps.sort(byId) }
}

/** The registry file's content for the library. */
export function registryOf(library: { registered: LibraryPackage[] }): { $comment: string; packages: Record<string, CompiledPackage>; reviews: Record<string, Drift> } {
  return {
    $comment: 'GENERATED by scripts/compile-implementation-content.mjs --registry from docs/implementation-content/. Do not edit by hand: src/content/implementation/library.test.ts fails when this file and its sources disagree.',
    packages: Object.fromEntries(library.registered.map((r) => [r.stepId, r.pkg])),
    reviews: Object.fromEntries(library.registered.map((r) => [r.stepId, r.drift])),
  }
}
