// The "Control Where People Sign In From" group, taken to the V1 standard:
// docs/plans/where-people-sign-in-spec.md holds the outcome, the Microsoft Learn
// page behind every technical claim and the date it was checked. One test per
// acceptance item in that spec.
//
// A test here reads the OPENED STEP wherever the claim is about what an admin
// sees, and the compiled package block where the claim is about a lifecycle
// state no fixture reaches — the same rule closeDoors.test.ts follows. One step
// of this group (`s-goal-workload-identity-block`) is generated by no fixture at
// all (spec section 9.5), so every claim about it is read from its content entry
// and its package, which are the text its print, export and prompt pack carry.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { stepById } from '../../content/content.ts'
import { fillText } from '../../content/render.ts'
import registry from '../../content/implementation/registry.generated.json' with { type: 'json' }
import { fixture } from '../../roadmap/fixtures/index.ts'
import type { Fixture, FixtureName } from '../../roadmap/fixtures/index.ts'
import { runFixture } from '../../roadmap/fixtures/run.ts'
import { setDisplayTimeZone } from '../../copy/dates.ts'
import { laneViewOf, prerequisiteLabelFor, readinessBlockersOf, waveStartOf } from './planBoard.ts'
import { laneReadings } from './planLanes.ts'
import { planDates } from './stepVars.ts'
import type { StepVarContext } from './stepVars.ts'
import { stepBodyOf } from './stepBody.ts'
import type { StepBody } from './stepBody.ts'
import { membersOf } from '../../roadmap/stepGroups.ts'
import type { MappingState } from '../../mapping/types.ts'

/** The group's six members, in registry order (roadmap/stepGroups.ts). */
const WHERE_SIGN_IN = [
  's-prereq-trusted-location',
  's-prereq-allowed-countries',
  's-goal-geo-restriction',
  's-prereq-service-accounts-group',
  's-goal-service-accounts-trusted-network',
  's-goal-workload-identity-block',
]

/** Every step's body on a fixture, as the Plan composes it (closeDoors.test.ts bodiesOf). */
function bodiesOf(name: FixtureName, mapping?: MappingState): Map<string, StepBody> {
  setDisplayTimeZone('UTC')
  try {
    const f: Fixture = mapping ? { ...fixture(name), mapping } : fixture(name)
    const r = runFixture(f, { mapping: f.mapping }, null, f.snapshot.asOf)
    const readings = laneReadings(r.steps, [])
    const titleOf = (id: string): string | null => r.steps.find((s) => s.id === id)?.title ?? null
    const dates = planDates(r.steps, r.schedule.start, r.coverage.organisation.naming, f.snapshot)
    const out = new Map<string, StepBody>()
    for (const step of r.steps) {
      const reading = readings.get(step.id)
      if (!reading) continue
      const lane = laneViewOf(reading, titleOf)
      const ctx: StepVarContext = { snapshot: f.snapshot, mapping: f.mapping, nameOf: (id) => r.input.names!.label(id), signature: 'IT', operatorId: f.operatorId, now: f.snapshot.asOf, ...dates, reportOnlyAt: step.reportOnlyAt ?? null, scheduledOn: waveStartOf(step), groups: f.groups, directory: r.input.directory, naming: r.coverage.organisation.naming }
      out.set(step.id, stepBodyOf(step, ctx, { lane, blockers: readinessBlockersOf(reading, titleOf), prerequisiteLabel: prerequisiteLabelFor(readings) }))
    }
    return out
  } finally {
    setDisplayTimeZone(null)
  }
}

/** A content step's own `why`, unfilled. */
const whyOf = (id: string): string => String((stepById[id] as unknown as { why?: string }).why ?? '')

/** The step's About sentence as the opened step fills it. */
const aboutOf = (b: StepBody): string => fillText(String((b.cs as Record<string, unknown>).why ?? ''), b.ex as Record<string, unknown>)

/** A step's risk lines from the content file, whatever their `applies`. */
const risksOf = (id: string): string[] =>
  (((stepById[id] as unknown as { more?: { risks?: { text?: string }[] } }).more?.risks ?? []).map((r) => r.text ?? '')) as string[]

/** A step's help-desk lines from the content file. */
const helpDeskOf = (id: string): string[] => ((stepById[id] as unknown as { more?: { helpDesk?: unknown } }).more?.helpDesk ?? []) as string[]

/** Every string a step's content entry carries, joined: the whole of what it can say. */
function allText(id: string): string {
  const out: string[] = []
  const walk = (n: unknown): void => {
    if (typeof n === 'string') out.push(n)
    else if (Array.isArray(n)) n.forEach(walk)
    else if (n && typeof n === 'object') for (const [k, v] of Object.entries(n)) if (k !== 'example') walk(v)
  }
  walk(stepById[id])
  return out.join('\n')
}

/** A compiled package block's authored text, for a lifecycle state no fixture reaches. */
function blockText(stepId: string, blockId: string): string {
  const pkg = (registry.packages as Record<string, { blocks?: Record<string, { text?: string }> }>)[stepId]
  const text = pkg?.blocks?.[blockId]?.text
  assert.ok(typeof text === 'string' && text !== '', `${stepId}: the package has no ${blockId} block`)
  return text as string
}

/** Every authored block of a package, joined. */
function packageText(stepId: string): string {
  const pkg = (registry.packages as Record<string, { blocks?: Record<string, { text?: string }> }>)[stepId]
  return Object.values(pkg?.blocks ?? {}).map((b) => b.text ?? '').join('\n')
}

/** The package's own last-checked date (project.ts sourceUpdatedOn reads the max). */
function checkedOn(stepId: string): string {
  const meta = (registry.packages as Record<string, { meta?: { verifiedSources?: { checkedOn: string }[] } }>)[stepId]?.meta
  const dates = (meta?.verifiedSources ?? []).map((s) => s.checkedOn).sort()
  return dates[dates.length - 1] ?? ''
}

// ---------------------------------------------------------------------------
// The group itself
// ---------------------------------------------------------------------------

test('the group draws its six members in the spec order', () => {
  assert.deepEqual([...membersOf('where-people-sign-in')], WHERE_SIGN_IN)
})

// ---------------------------------------------------------------------------
// Define the Trusted Network (spec section 3)
// ---------------------------------------------------------------------------

test('T1: the create procedure opens at the path Microsoft names, with Entra ID in it', () => {
  assert.match(blockText('s-prereq-trusted-location', 'entra.create'), /\*\*Entra admin center → Entra ID → Conditional Access → Named locations → \+ IP ranges location\*\*/)
  // And the step's own instruction lines say the same route.
  assert.match(allText('s-prereq-trusted-location'), /Entra admin center → Entra ID → Conditional Access → Named locations/)
})

test('T2: no risk claims a trusted location lowers a risk score; one says what it really does', () => {
  const risks = risksOf('s-prereq-trusted-location')
  assert.ok(risks.some((t) => /improve the accuracy of Microsoft Entra ID Protection's risk calculation/.test(t)), risks.join('\n'))
  assert.ok(!risks.some((t) => /lowers Identity Protection risk scores/.test(t)), risks.join('\n'))
})

test('T3: the create procedure states the mask rule Entra enforces, not a range it refuses', () => {
  assert.match(blockText('s-prereq-trusted-location', 'entra.create'), /masks greater than \/8/)
  assert.match(allText('s-prereq-trusted-location'), /Entra accepts only masks greater than \/8, and no more than two thousand ranges in one location\./)
  assert.doesNotMatch(allText('s-prereq-trusted-location'), /never 0\.0\.0\.0\/0/)
})

test('T4: the step says a trusted location cannot be deleted while the trusted mark is on it', () => {
  assert.ok(risksOf('s-prereq-trusted-location').some((t) => /cannot be deleted until the trusted mark is removed/.test(t)), risksOf('s-prereq-trusted-location').join('\n'))
  assert.match(blockText('s-prereq-trusted-location', 'entra.correct.trusted'), /cannot be deleted until the mark is taken off/)
})

test('T5: the step names both steps that wait on it', () => {
  const waits = String((stepById['s-prereq-trusted-location'] as unknown as { more?: { waits?: string } }).more?.waits ?? '')
  assert.match(waits, /Protect Sign-in Method Registration and Restrict Service Accounts to the Trusted Network wait on this\./)
})

test('T6: the step shows the date its Microsoft sources were checked, on both scans', () => {
  assert.equal(checkedOn('s-prereq-trusted-location'), '2026-09-20')
  assert.equal(bodiesOf('demo').get('s-prereq-trusted-location')!.sourceLine, 'Source checked Sep 20, 2026')
  // The follow-up scan has the object in place; the line is the same.
  assert.equal(bodiesOf('demo-week2').get('s-prereq-trusted-location')!.sourceLine, 'Source checked Sep 20, 2026')
})

test('T7: Done when opens on this step’s outcome, on screen', () => {
  const done = bodiesOf('demo').get('s-prereq-trusted-location')!.contract.doneWhen
  assert.ok(done.some((l: string) => /holds exactly the public ranges the network owner approved, and it is marked as trusted/.test(l)), done.join('\n'))
  assert.ok(!done.some((l: string) => /A trusted IP named location exists in the tenant\./.test(l)), done.join('\n'))
})

// ---------------------------------------------------------------------------
// Create or Correct Allowed Countries Location (spec section 4)
// ---------------------------------------------------------------------------

test('A1: nothing tells anyone not to mark a countries location trusted, and the step says where trust belongs', () => {
  const all = allText('s-prereq-allowed-countries')
  assert.doesNotMatch(all, /Do not mark it as trusted/)
  assert.match(all, /trust belongs to the IP ranges location Define the Trusted Network creates/)
  assert.match(blockText('s-prereq-allowed-countries', 'entra.create'), /no trusted mark on a countries location/)
})

test('A2: the step says what Determine location by GPS coordinates would require', () => {
  assert.ok(
    risksOf('s-prereq-allowed-countries').some((t) => /asks each person's Microsoft Authenticator app for a location every hour/.test(t)),
    risksOf('s-prereq-allowed-countries').join('\n'),
  )
  assert.match(blockText('s-prereq-allowed-countries', 'entra.create'), /\*\*Determine location by GPS coordinates\*\*, asks each person's Microsoft Authenticator app/)
})

test('A3: the step says how country is worked out from an address', () => {
  assert.match(allText('s-prereq-allowed-countries'), /resolves the sign-in's IPv4 or IPv6 address to a country using a mapping table Microsoft updates periodically/)
  assert.match(blockText('s-prereq-allowed-countries', 'entra.create'), /mapping table Microsoft updates periodically/)
})

test('A4: the row’s Impact has one source, and it is the word the row draws', () => {
  const meta = (registry.packages as Record<string, { meta?: { impact?: { fallbackLabel?: string } } }>)['s-prereq-allowed-countries']?.meta
  assert.equal(meta?.impact?.fallbackLabel, 'Allowed countries')
})

test('A5: the step shows the date its Microsoft sources were checked, on both scans', () => {
  assert.equal(checkedOn('s-prereq-allowed-countries'), '2026-09-20')
  assert.equal(bodiesOf('demo').get('s-prereq-allowed-countries')!.sourceLine, 'Source checked Sep 20, 2026')
  assert.equal(bodiesOf('demo-week2').get('s-prereq-allowed-countries')!.sourceLine, 'Source checked Sep 20, 2026')
})

test('A6: Done when opens on this step’s outcome, on screen', () => {
  const done = bodiesOf('demo').get('s-prereq-allowed-countries')!.contract.doneWhen
  assert.ok(done.some((l: string) => /lists exactly .+, the countries people work from/.test(l)), done.join('\n'))
  assert.ok(done.some((l: string) => /a sign-in whose country cannot be worked out stays outside the list/.test(l)), done.join('\n'))
})

// ---------------------------------------------------------------------------
// Block Sign-ins From Countries Not Allowed (spec section 5)
// ---------------------------------------------------------------------------

test('G1: the network condition is set through Configure: Yes, in create and in correct', () => {
  const create = blockText('s-goal-geo-restriction', 'entra.create')
  assert.match(create, /set \*\*Configure\*\* to \*\*Yes\*\*/)
  assert.match(create, /Left at \*\*No\*\* the network condition is not configured/)
  assert.match(blockText('s-goal-geo-restriction', 'entra.correct-conditions'), /set \*\*Configure\*\* to \*\*Yes\*\*/)
  // And the reviewer's transcription of the same policy says it too.
  assert.match(allText('geo-restriction'), /Configure: Yes, then Include: Any network or location/)
})

test('G2: no procedure of this step says "Any location"; the current label is used', () => {
  assert.doesNotMatch(packageText('s-goal-geo-restriction').replace(/Any network or location/g, ''), /Any location/)
  assert.doesNotMatch(allText('geo-restriction').replace(/Any network or location/g, ''), /Any location/)
})

test('G3: a risk names the header Conditional Access ignores behind a proxy', () => {
  assert.ok(
    risksOf('geo-restriction').some((t) => /ignores the X-Forwarded-For header that carries the person's/.test(t)),
    risksOf('geo-restriction').join('\n'),
  )
})

test('G4: a risk says when the rule bites, not just that it is not instant', () => {
  assert.ok(risksOf('geo-restriction').some((t) => /reissued, which is hourly by default/.test(t)), risksOf('geo-restriction').join('\n'))
  assert.ok(!risksOf('geo-restriction').some((t) => /does not bite until the token refreshes/.test(t)), risksOf('geo-restriction').join('\n'))
})

test('G5: help desk says this policy does not reach a service principal, and names the step that does', () => {
  const lines = helpDeskOf('geo-restriction')
  assert.ok(lines.some((l) => /a call made by a service principal is not blocked by a policy scoped to users/.test(l)), lines.join('\n'))
  assert.ok(lines.some((l) => /Restrict the Entra Connect Sync Account to Its Address/.test(l)), lines.join('\n'))
  assert.ok(lines.some((l) => /Directory Synchronization Accounts directory role/.test(l)), lines.join('\n'))
})

test('G6: the held step’s Completion Criteria is this step’s outcome, on screen and on both scans', () => {
  for (const f of ['demo', 'demo-week2'] as const) {
    const done = bodiesOf(f).get('s-goal-geo-restriction')!.contract.doneWhen
    assert.ok(done.some((l: string) => /^Nobody signs in to .+ from a country that is not on the approved list/.test(l)), `${f}: ${done.join('\n')}`)
    assert.ok(!done.some((l: string) => /blocking sign-ins from countries not in the allowed list/.test(l)), `${f}: ${done.join('\n')}`)
  }
})

test('G7: the step shows the date its Microsoft sources were checked, on both scans', () => {
  assert.equal(checkedOn('s-goal-geo-restriction'), '2026-09-20')
  assert.equal(bodiesOf('demo').get('s-goal-geo-restriction')!.sourceLine, 'Source checked Sep 20, 2026')
  assert.equal(bodiesOf('demo-week2').get('s-goal-geo-restriction')!.sourceLine, 'Source checked Sep 20, 2026')
})
