// The "Control Where People Sign In From" steps, taken to the V1 standard:
// docs/plans/where-people-sign-in-spec.md holds the outcome, the Microsoft Learn
// page behind every technical claim and the date it was checked. One test per
// acceptance item in that spec.
//
// A test here reads the OPENED STEP wherever the claim is about what an admin
// sees, and the compiled package block where the claim is about a lifecycle
// state no fixture reaches — the same rule closeDoors.test.ts follows. One step
// of this group (`s-goal-workload-identity-block`) is generated by no fixture at
// all (spec section 9.5), so every claim about it is read from its content entry
// and its package, which are the text its print, export and prompt pack carry.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { stepById } from '../../content/content.ts'
import { fillText } from '../../content/render.ts'
import registry from '../../content/implementation/registry.generated.json' with { type: 'json' }
import { fixture } from '../../roadmap/fixtures/index.ts'
import type { Fixture, FixtureName } from '../../roadmap/fixtures/index.ts'
import { runFixture } from '../../roadmap/fixtures/run.ts'
import { setDisplayTimeZone } from '../../copy/dates.ts'
import { laneViewOf, prerequisiteLabelFor, readinessBlockersOf, waveStartOf } from './planBoard.ts'
import { laneReadings } from './planLanes.ts'
import { planDates } from './stepVars.ts'
import type { StepVarContext } from './stepVars.ts'
import { stepBodyOf } from './stepBody.ts'
import { stepExportView } from './stepExport.ts'
import type { StepBody } from './stepBody.ts'
import { groupOf } from '../../roadmap/stepGroups.ts'
import type { MappingState } from '../../mapping/types.ts'

/** The spec's three policy steps (docs/plans/where-people-sign-in-spec.md), in its order. */
const WHERE_SIGN_IN = [
  's-goal-geo-restriction',
  's-goal-service-accounts-trusted-network',
  's-goal-workload-identity-block',
]

/** The three objects a Direction answer asks for, which sit among the objects before any policy (owner, 2026-09-20; roadmap flow section 3). */
const PREPARE_OBJECTS = [
  's-prereq-trusted-location',
  's-prereq-allowed-countries',
  's-prereq-service-accounts-group',
]

/** Every step's body on a fixture, as the Plan composes it (closeDoors.test.ts bodiesOf). */
function bodiesOf(name: FixtureName, mapping?: MappingState): Map<string, StepBody> {
  setDisplayTimeZone('UTC')
  try {
    const f: Fixture = mapping ? { ...fixture(name), mapping } : fixture(name)
    const r = runFixture(f, { mapping: f.mapping }, null, f.snapshot.asOf)
    const readings = laneReadings(r.steps, [])
    const titleOf = (id: string): string | null => r.steps.find((s) => s.id === id)?.title ?? null
    const dates = planDates(r.steps, r.schedule.start, r.coverage.organisation.naming, f.snapshot)
    const out = new Map<string, StepBody>()
    for (const step of r.steps) {
      const reading = readings.get(step.id)
      if (!reading) continue
      const lane = laneViewOf(reading, titleOf)
      const ctx: StepVarContext = { snapshot: f.snapshot, mapping: f.mapping, nameOf: (id) => r.input.names!.label(id), signature: 'IT', operatorId: f.operatorId, now: f.snapshot.asOf, ...dates, reportOnlyAt: step.reportOnlyAt ?? null, scheduledOn: waveStartOf(step), groups: f.groups, directory: r.input.directory, naming: r.coverage.organisation.naming }
      out.set(step.id, stepBodyOf(step, ctx, { lane, blockers: readinessBlockersOf(reading, titleOf), prerequisiteLabel: prerequisiteLabelFor(readings) }))
    }
    return out
  } finally {
    setDisplayTimeZone(null)
  }
}

/** A content step's own `why`, unfilled: the words About this Step draws. */
const whyOf = (id: string): string => String((stepById[id] as unknown as { why?: string }).why ?? '')

/** The step's About sentence as the OPENED step fills it, which is what a person reads. */
const aboutOf = (b: StepBody): string => fillText(String((b.cs as Record<string, unknown>).why ?? ''), b.ex as Record<string, unknown>)

/** A step's risk lines from the content file, whatever their `applies`. */
const risksOf = (id: string): string[] =>
  (((stepById[id] as unknown as { more?: { risks?: { text?: string }[] } }).more?.risks ?? []).map((r) => r.text ?? '')) as string[]

/** A step's help-desk lines from the content file. */
const helpDeskOf = (id: string): string[] => ((stepById[id] as unknown as { more?: { helpDesk?: unknown } }).more?.helpDesk ?? []) as string[]

/** Every string a step's content entry carries, joined: the whole of what it can say. */
function allText(id: string): string {
  const out: string[] = []
  const walk = (n: unknown): void => {
    if (typeof n === 'string') out.push(n)
    else if (Array.isArray(n)) n.forEach(walk)
    else if (n && typeof n === 'object') for (const [k, v] of Object.entries(n)) if (k !== 'example') walk(v)
  }
  walk(stepById[id])
  return out.join('\n')
}

/** A compiled package block's authored text, for a lifecycle state no fixture reaches. */
function blockText(stepId: string, blockId: string): string {
  const pkg = (registry.packages as Record<string, { blocks?: Record<string, { text?: string }> }>)[stepId]
  const text = pkg?.blocks?.[blockId]?.text
  assert.ok(typeof text === 'string' && text !== '', `${stepId}: the package has no ${blockId} block`)
  return text as string
}

/** Every authored block of a package, joined. */
function packageText(stepId: string): string {
  const pkg = (registry.packages as Record<string, { blocks?: Record<string, { text?: string }> }>)[stepId]
  return Object.values(pkg?.blocks ?? {}).map((b) => b.text ?? '').join('\n')
}

/** The package's own last-checked date (project.ts sourceUpdatedOn reads the max). */
function checkedOn(stepId: string): string {
  const meta = (registry.packages as Record<string, { meta?: { verifiedSources?: { checkedOn: string }[] } }>)[stepId]?.meta
  const dates = (meta?.verifiedSources ?? []).map((s) => s.checkedOn).sort()
  return dates[dates.length - 1] ?? ''
}

// ---------------------------------------------------------------------------
// The group itself
// ---------------------------------------------------------------------------

test('the spec’s three policies close the doors, and the objects they reference are prepared before any policy', () => {
  assert.deepEqual(WHERE_SIGN_IN.map((id) => groupOf(id)?.key), ['remaining-doors', 'remaining-doors', 'remaining-doors'])
  assert.deepEqual(PREPARE_OBJECTS.map((id) => groupOf(id)?.key), ['prepare', 'prepare', 'prepare'])
  // The spec's six steps are still the same six steps, read in the same order:
  // the objects first, then the policies that reference them.
  assert.deepEqual([...PREPARE_OBJECTS, ...WHERE_SIGN_IN].sort(), ['s-goal-geo-restriction', 's-goal-service-accounts-trusted-network', 's-goal-workload-identity-block', 's-prereq-allowed-countries', 's-prereq-service-accounts-group', 's-prereq-trusted-location'])
})

// ---------------------------------------------------------------------------
// Define the Trusted Network (spec section 3)
// ---------------------------------------------------------------------------

test('T1: the create procedure opens at the path Microsoft names, with Entra ID in it', () => {
  assert.match(blockText('s-prereq-trusted-location', 'entra.create'), /\*\*Entra admin center → Entra ID → Conditional Access → Named locations → \+ IP ranges location\*\*/)
  // And the step's own instruction lines say the same route.
  assert.match(allText('s-prereq-trusted-location'), /Entra admin center → Entra ID → Conditional Access → Named locations/)
})

test('T2: no risk claims a trusted location lowers a risk score; one says what it really does', () => {
  const risks = risksOf('s-prereq-trusted-location')
  assert.ok(risks.some((t) => /improve the accuracy of Microsoft Entra ID Protection's risk calculation/.test(t)), risks.join('\n'))
  assert.ok(!risks.some((t) => /lowers Identity Protection risk scores/.test(t)), risks.join('\n'))
})

test('T3: the create procedure states the mask rule Entra enforces, not a range it refuses', () => {
  assert.match(blockText('s-prereq-trusted-location', 'entra.create'), /masks greater than \/8/)
  assert.match(allText('s-prereq-trusted-location'), /Entra accepts only masks greater than \/8, and no more than two thousand ranges in one location\./)
  assert.doesNotMatch(allText('s-prereq-trusted-location'), /never 0\.0\.0\.0\/0/)
})

test('T4: the step says a trusted location cannot be deleted while the trusted mark is on it', () => {
  assert.ok(risksOf('s-prereq-trusted-location').some((t) => /cannot be deleted until the trusted mark is removed/.test(t)), risksOf('s-prereq-trusted-location').join('\n'))
  assert.match(blockText('s-prereq-trusted-location', 'entra.correct.trusted'), /cannot be deleted until the mark is taken off/)
})

test('T5: the step names every step that waits on it, which the board proves is four', () => {
  const waits = String((stepById['s-prereq-trusted-location'] as unknown as { more?: { waits?: string } }).more?.waits ?? '')
  // The demo's board holds exactly these four waiting on this object.
  const waiting = ['s-shared-devices', 's-goal-register-info-protected', 's-goal-require-managed-device', 's-goal-service-accounts-trusted-network']
  const bodies = bodiesOf('demo')
  for (const id of waiting) {
    const tiles = JSON.stringify(bodies.get(id)!.allTiles)
    assert.match(tiles, /Define the Trusted Network/, `${id}: the board does not show it waiting on the trusted network`)
    assert.ok(waits.includes(bodies.get(id)!.title), `${waits}\n  does not name ${bodies.get(id)!.title}`)
  }
})

test('T6: the step shows the date its Microsoft sources were checked, on both scans', () => {
  assert.equal(checkedOn('s-prereq-trusted-location'), '2026-09-20')
  assert.equal(bodiesOf('demo').get('s-prereq-trusted-location')!.sourceLine, 'Source checked Sep 20, 2026')
  // The follow-up scan has the object in place; the line is the same.
  assert.equal(bodiesOf('demo-week2').get('s-prereq-trusted-location')!.sourceLine, 'Source checked Sep 20, 2026')
})

test('T7: Done when opens on this step’s outcome, on screen', () => {
  const done = bodiesOf('demo').get('s-prereq-trusted-location')!.contract.doneWhen
  assert.ok(done.some((l: string) => /holds exactly the public ranges the network owner approved, and it is marked as trusted/.test(l)), done.join('\n'))
  assert.ok(!done.some((l: string) => /A trusted IP named location exists in the tenant\./.test(l)), done.join('\n'))
})

// ---------------------------------------------------------------------------
// Create or Correct Allowed Countries Location (spec section 4)
// ---------------------------------------------------------------------------

test('A1: nothing tells anyone not to mark a countries location trusted, and the step says where trust belongs', () => {
  const all = allText('s-prereq-allowed-countries')
  assert.doesNotMatch(all, /Do not mark it as trusted/)
  assert.match(all, /trust belongs to the IP ranges location Define the Trusted Network creates/)
  assert.match(blockText('s-prereq-allowed-countries', 'entra.create'), /no trusted mark on a countries location/)
})

test('A2: the step says what Determine location by GPS coordinates would require', () => {
  assert.ok(
    risksOf('s-prereq-allowed-countries').some((t) => /asks each person's Microsoft Authenticator app for a location every hour/.test(t)),
    risksOf('s-prereq-allowed-countries').join('\n'),
  )
  assert.match(blockText('s-prereq-allowed-countries', 'entra.create'), /\*\*Determine location by GPS coordinates\*\*, asks each person's Microsoft Authenticator app/)
})

test('A3: the step says how country is worked out from an address', () => {
  assert.match(allText('s-prereq-allowed-countries'), /resolves the sign-in's IPv4 or IPv6 address to a country using a mapping table Microsoft updates periodically/)
  assert.match(blockText('s-prereq-allowed-countries', 'entra.create'), /mapping table Microsoft updates periodically/)
})

test('A4: the row’s Impact has one source, and it is the word the row draws', () => {
  const meta = (registry.packages as Record<string, { meta?: { impact?: { fallbackLabel?: string } } }>)['s-prereq-allowed-countries']?.meta
  assert.equal(meta?.impact?.fallbackLabel, 'Allowed countries')
})

test('A5: the step shows the date its Microsoft sources were checked, on both scans', () => {
  assert.equal(checkedOn('s-prereq-allowed-countries'), '2026-09-20')
  assert.equal(bodiesOf('demo').get('s-prereq-allowed-countries')!.sourceLine, 'Source checked Sep 20, 2026')
  assert.equal(bodiesOf('demo-week2').get('s-prereq-allowed-countries')!.sourceLine, 'Source checked Sep 20, 2026')
})

test('A6: Done when opens on this step’s outcome, on screen', () => {
  const done = bodiesOf('demo').get('s-prereq-allowed-countries')!.contract.doneWhen
  assert.ok(done.some((l: string) => /lists exactly .+, the countries people work from/.test(l)), done.join('\n'))
  assert.ok(done.some((l: string) => /a sign-in whose country cannot be worked out stays outside the list/.test(l)), done.join('\n'))
})

// ---------------------------------------------------------------------------
// Block Sign-ins From Countries Not Allowed (spec section 5)
// ---------------------------------------------------------------------------

test('G1: the network condition is set through Configure: Yes, in create and in correct', () => {
  const create = blockText('s-goal-geo-restriction', 'entra.create')
  assert.match(create, /set \*\*Configure\*\* to \*\*Yes\*\*/)
  assert.match(create, /Left at \*\*No\*\* the network condition is not configured/)
  assert.match(blockText('s-goal-geo-restriction', 'entra.correct-conditions'), /set \*\*Configure\*\* to \*\*Yes\*\*/)
  // And the reviewer's transcription of the same policy says it too.
  assert.match(allText('geo-restriction'), /Configure: Yes, then Include: Any network or location/)
})

test('G2: no procedure of this step says "Any location"; the current label is used', () => {
  assert.doesNotMatch(packageText('s-goal-geo-restriction').replace(/Any network or location/g, ''), /Any location/)
  assert.doesNotMatch(allText('geo-restriction').replace(/Any network or location/g, ''), /Any location/)
})

test('G3: a risk names the header Conditional Access ignores behind a proxy', () => {
  assert.ok(
    risksOf('geo-restriction').some((t) => /ignores the X-Forwarded-For header that carries the person's/.test(t)),
    risksOf('geo-restriction').join('\n'),
  )
})

test('G4: a risk says when the rule bites, not just that it is not instant', () => {
  assert.ok(risksOf('geo-restriction').some((t) => /reissued, which is hourly by default/.test(t)), risksOf('geo-restriction').join('\n'))
  assert.ok(!risksOf('geo-restriction').some((t) => /does not bite until the token refreshes/.test(t)), risksOf('geo-restriction').join('\n'))
})

test('G5: help desk says this policy does not reach a service principal, and names the step that does', () => {
  const lines = helpDeskOf('geo-restriction')
  assert.ok(lines.some((l) => /a call made by a service principal is not blocked by a policy scoped to users/.test(l)), lines.join('\n'))
  assert.ok(lines.some((l) => /Restrict the Directory Sync Service Principal to Its Address/.test(l)), lines.join('\n'))
  assert.ok(lines.some((l) => /Directory Synchronization Accounts directory role/.test(l)), lines.join('\n'))
})

test('G6: the held step’s Completion Criteria is this step’s outcome, on screen and on both scans', () => {
  for (const f of ['demo', 'demo-week2'] as const) {
    const done = bodiesOf(f).get('s-goal-geo-restriction')!.contract.doneWhen
    assert.ok(done.some((l: string) => /^Nobody signs in to .+ from a country that is not on the approved list/.test(l)), `${f}: ${done.join('\n')}`)
    assert.ok(!done.some((l: string) => /blocking sign-ins from countries not in the allowed list/.test(l)), `${f}: ${done.join('\n')}`)
  }
})

test('G7: the step shows the date its Microsoft sources were checked, on both scans', () => {
  assert.equal(checkedOn('s-goal-geo-restriction'), '2026-09-20')
  assert.equal(bodiesOf('demo').get('s-goal-geo-restriction')!.sourceLine, 'Source checked Sep 20, 2026')
  assert.equal(bodiesOf('demo-week2').get('s-goal-geo-restriction')!.sourceLine, 'Source checked Sep 20, 2026')
})

// ---------------------------------------------------------------------------
// Create or Correct Service Accounts Group (spec section 6)
// ---------------------------------------------------------------------------

test('S1: the step says a policy assigned to a group is not enforced for a service principal in it', () => {
  assert.ok(
    risksOf('s-prereq-service-accounts-group').some((t) => /assigned to a group is not enforced for a service principal in that group/.test(t)),
    risksOf('s-prereq-service-accounts-group').join('\n'),
  )
  assert.match(blockText('s-prereq-service-accounts-group', 'entra.create'), /not enforced for a service principal inside it/)
})

test('S2: the step says why a service principal is out of a user-scoped policy’s reach', () => {
  const help = String((stepById['s-prereq-service-accounts-group'] as unknown as { decision?: { help?: string } }).decision?.help ?? '')
  assert.match(help, /a policy scoped to users does not block a call made by a service principal/)
  assert.match(blockText('s-prereq-service-accounts-group', 'entra.create'), /does not block a call made by a service principal/)
})

test('S3: the step says the mail-sending devices from Confirm What You Use are in this group', () => {
  // The merge itself is a frozen step's behaviour (docs/plans/frozen-step-suggestions.md
  // section 8) and is unchanged; what changed is that this step explains the count.
  assert.match(allText('s-prereq-service-accounts-group'), /named as a mail-sending device in Confirm What You Use is already on that list/)
  assert.match(blockText('s-prereq-service-accounts-group', 'entra.create'), /named as a mail-sending device in Confirm What You Use is already on that list/)
  const done = bodiesOf('demo').get('s-prereq-service-accounts-group')!.contract.doneWhen
  assert.ok(done.some((l: string) => /the mail-sending devices named in Confirm What You Use among them/.test(l)), done.join('\n'))
})

// The sentence pointed at "that list" from a line of its own, and the list line
// it pointed at goes where no account is nominated (stepInstructions.ts
// wholeLines, the one gate for the screen and the export). On every fixture with
// none (small, getiamai, large, messy, midflight, hostile) the step said "Any
// account named as a mail-sending device in Confirm What You Use is already on
// that list." under the group's name, with no list anywhere: on the screen, in
// its task and in the export. It rides the list's own line now, so the one gate
// takes both.
test('S3a: the mail-sending sentence goes with the list it points at', () => {
  const surfaces = (name: FixtureName): string[] => {
    const f = fixture(name)
    const r = runFixture(f, { mapping: f.mapping }, null, f.snapshot.asOf)
    const step = r.steps.find((x) => x.id === 's-prereq-service-accounts-group')!
    const ctx: StepVarContext = { snapshot: f.snapshot, mapping: f.mapping, nameOf: (id) => r.input.names!.label(id), signature: 'IT', operatorId: f.operatorId, now: f.snapshot.asOf, ...planDates(r.steps, r.schedule.start, r.coverage.organisation.naming, f.snapshot), groups: f.groups, directory: r.input.directory, naming: r.coverage.organisation.naming }
    const b = stepBodyOf(step, ctx)
    return [...b.artifacts.map((a) => a.text()), ...(b.emergencyAccountTasks?.tasks ?? []).flatMap((t) => t.steps), ...stepExportView(step, ctx).whatToDo].flatMap((t) => t.split('\n'))
  }
  for (const name of ['small', 'getiamai', 'hostile'] as const) {
    const lines = surfaces(name)
    assert.ok(lines.some((l) => /New group → Security/.test(l)), `${name}: the premise, the step's own lines are drawn`)
    assert.ok(!lines.some((l) => /already on that list/.test(l)), `${name}: "that list" with no list: ${lines.find((l) => /already on that list/.test(l))}`)
  }
  // Where accounts are nominated, the sentence follows the list it names.
  const demo = surfaces('demo').filter((l) => /already on that list/.test(l))
  assert.ok(demo.length > 0, 'demo nominates service accounts')
  for (const line of demo) assert.match(line, /svc-mailer-1.*svc-mailer-2.*\. Any account named as a mail-sending device/, line)
})

test('S4: the sibling policies are named once in the step, and are the ones that really wait', () => {
  const waits = String((stepById['s-prereq-service-accounts-group'] as unknown as { more?: { waits?: string } }).more?.waits ?? '')
  assert.equal(waits, 'Restrict Service Accounts to the Trusted Network and Require Token Protection on Windows wait on this.')
  // The risk beside it no longer repeats that list.
  const risks = risksOf('s-prereq-service-accounts-group').join('\n')
  assert.ok(!/Block Legacy Authentication/.test(risks) && !/Block Sign-ins From Countries Not Allowed/.test(risks), risks)
  assert.ok(!/Require Token Protection on Windows/.test(risks), risks)
  // And the board agrees: on the mid plan both named steps wait on this object.
  const mid = bodiesOf('mid')
  for (const id of ['s-goal-service-accounts-trusted-network', 's-goal-token-protection']) {
    assert.match(JSON.stringify(mid.get(id)!.allTiles), /Create or Correct Service Accounts Group/, id)
  }
})

test('S5: the package carries a dated Microsoft Learn source, where it carried none', () => {
  assert.equal(checkedOn('s-prereq-service-accounts-group'), '2026-09-20')
  assert.equal(bodiesOf('demo').get('s-prereq-service-accounts-group')!.sourceLine, 'Source checked Sep 20, 2026')
})

// ---------------------------------------------------------------------------
// Restrict Service Accounts to the Trusted Network (spec section 7)
// ---------------------------------------------------------------------------

test('N1: the held step’s Completion Criteria is this step’s outcome, not the shared sentence', () => {
  for (const f of ['demo', 'demo-week2'] as const) {
    const done = bodiesOf(f).get('s-goal-service-accounts-trusted-network')!.contract.doneWhen
    assert.ok(done.some((l: string) => /can sign in to .+ only from the approved trusted network, and every job that uses one has been run from there and recorded/.test(l)), `${f}: ${done.join('\n')}`)
    assert.ok(!done.some((l: string) => /^The policy is enforced in .+\.$/.test(l)), `${f}: ${done.join('\n')}`)
  }
})

test('N2: the network condition is set through Configure: Yes, in create and in correct', () => {
  const create = blockText('s-goal-service-accounts-trusted-network', 'entra.create')
  assert.match(create, /set \*\*Configure\*\* to \*\*Yes\*\*/)
  assert.match(create, /Left at \*\*No\*\* the network condition is not configured/)
  assert.match(blockText('s-goal-service-accounts-trusted-network', 'entra.correct.network'), /set \*\*Configure\*\* to \*\*Yes\*\*/)
  assert.match(allText('service-accounts-trusted-network'), /Configure: Yes, then Include: Any network or location/)
})

test('N3: no procedure of this step uses an old location label', () => {
  const text = packageText('s-goal-service-accounts-trusted-network').replace(/Any network or location/g, '')
  assert.doesNotMatch(text, /Any network\/location/)
  assert.doesNotMatch(allText('service-accounts-trusted-network').replace(/Any network or location/g, ''), /Any location/)
})

test('N4: the step’s Learn link is the page that documents the condition it uses', () => {
  const b = bodiesOf('demo').get('s-goal-service-accounts-trusted-network')!
  assert.equal(b.learnUrl, 'https://learn.microsoft.com/entra/identity/conditional-access/concept-assignment-network')
  const meta = (registry.packages as Record<string, { meta?: { verifiedSources?: { url: string }[] } }>)['s-goal-service-accounts-trusted-network']?.meta
  assert.ok((meta?.verifiedSources ?? []).some((s) => s.url === b.learnUrl), 'the package cites a different page from the step')
  // The four-year-old architecture page stays where it is about: which accounts.
  assert.equal(String((stepById['s-prereq-service-accounts-group'] as unknown as { learn?: { url?: string } }).learn?.url), 'https://learn.microsoft.com/entra/architecture/secure-service-accounts')
})

test('N5: the manager line names where a service principal is covered instead', () => {
  const manager = String((stepById['service-accounts-trusted-network'] as unknown as { more?: { manager?: string } }).more?.manager ?? '')
  assert.match(manager, /not blocked by a policy scoped to users/)
  assert.match(manager, /Restrict the Directory Sync Service Principal to Its Address/)
  assert.match(blockText('s-goal-service-accounts-trusted-network', 'entra.prerequisites'), /not enforced for a service principal inside it/)
})

test('N6: the step shows the date its Microsoft sources were checked, on both scans', () => {
  assert.equal(checkedOn('s-goal-service-accounts-trusted-network'), '2026-09-20')
  for (const f of ['demo', 'demo-week2'] as const) {
    assert.equal(bodiesOf(f).get('s-goal-service-accounts-trusted-network')!.sourceLine, 'Source checked Sep 20, 2026')
  }
})

// ---------------------------------------------------------------------------
// Restrict the Directory Sync Service Principal to Its Address (spec section 8)
//
// No fixture generates this step (spec section 9.5: it needs the Workload ID
// Premium licence beside D1's Entra Connect answer, and no fixture supplies
// both). Every claim below is therefore read from the content entry and the
// compiled package — the text the printed plan, the export and the prompt pack
// carry, and the text the step would draw wherever it is reached.
// ---------------------------------------------------------------------------

test('N7: About this Step still reads as its own sentence on screen, on both scans', () => {
  for (const f of ['demo', 'demo-week2'] as const) {
    const about = aboutOf(bodiesOf(f).get('s-goal-service-accounts-trusted-network')!)
    assert.match(about, /^Restricting user-based service accounts to approved networks can reduce where their passwords are useful\./)
    assert.doesNotMatch(about, /\{[^}]+\}/, 'an unfilled placeholder reached the screen')
  }
})

test('W0: the premise — no fixture draws this step, so its words are read where they are carried', () => {
  for (const f of ['demo', 'demo-week2', 'mid', 'messy', 'large'] as const) {
    assert.equal(bodiesOf(f).get('s-goal-workload-identity-block'), undefined, `${f} generates it after all; read the rendered body instead`)
  }
})

test('W1: the step states which identities a workload policy covers, and which it never does', () => {
  const why = whyOf('workload-identity-block')
  assert.match(why, /covers a single-tenant service principal registered in this tenant/)
  assert.match(why, /no Microsoft or multitenant application and no managed identity/)
  assert.match(blockText('s-goal-workload-identity-block', 'entra.policy.create'), /\*\*single-tenant service principal registered in this tenant\*\*/)
  assert.ok(
    helpDeskOf('workload-identity-block').some((l) => /A Microsoft or multitenant application, and any managed identity, is outside what this policy can cover/.test(l)),
    helpDeskOf('workload-identity-block').join('\n'),
  )
})

test('W2: a risk says a policy assigned to a group is not enforced for a service principal in it', () => {
  assert.ok(
    risksOf('workload-identity-block').some((t) => /assigned to a group that holds one is not enforced for it/.test(t)),
    risksOf('workload-identity-block').join('\n'),
  )
  assert.match(blockText('s-goal-workload-identity-block', 'entra.policy.create'), /a policy assigned to a group that holds a service principal is not enforced for that service principal/)
})

test('W3: the procedure says Block access is the only grant this policy offers', () => {
  assert.match(blockText('s-goal-workload-identity-block', 'entra.policy.create'), /It is the only grant control a workload identity policy offers\./)
  assert.match(allText('workload-identity-block'), /which is the only grant a workload identity policy offers/)
})

test('W4: the network condition is set through Configure: Yes, and is named by both its names', () => {
  const create = blockText('s-goal-workload-identity-block', 'entra.policy.create')
  assert.match(create, /\*\*Network\*\* \(this page still calls it \*\*Conditions > Locations\*\*\)/)
  assert.match(create, /set \*\*Configure\*\* to \*\*Yes\*\*/)
  assert.match(blockText('s-goal-workload-identity-block', 'entra.correct.policy.location-boundary'), /set \*\*Configure\*\* to \*\*Yes\*\*/)
  assert.match(allText('workload-identity-block'), /Network \(formerly Conditions → Locations\) → Configure: Yes, then Include: Any network or location/)
})

test('W5: the step says the Connect Sync account and the Cloud Sync service principal are two identities', () => {
  assert.match(whyOf('workload-identity-block'), /Entra Connect Sync signs in as a user account, while Cloud Sync uses a provisioning service principal/)
  assert.match(blockText('s-goal-workload-identity-block', 'entra.policy.create'), /user account with the Directory Synchronization Accounts role, while Cloud Sync uses a provisioning service principal/)
  // The Who line still carries the two sentences walkContent C6 reads off the pinned baseline.
  const who = allText('workload-identity-block')
  assert.match(who, /Cloud Sync's provisioning service principal/)
  assert.match(who, /does not establish support for workload Conditional Access/)
})

test('W6: the row’s Impact is about this step, not the placeholder', () => {
  const meta = (registry.packages as Record<string, { meta?: { impact?: { fallbackLabel?: string } } }>)['s-goal-workload-identity-block']?.meta
  assert.equal(meta?.impact?.fallbackLabel, 'Directory synchronisation')
  assert.notEqual(meta?.impact?.fallbackLabel, 'Tenant settings')
})

test('W7: the held step’s end state is this step’s outcome, and the caveat is said once', () => {
  const end = String((stepById['workload-identity-block'] as unknown as { doneEnd?: string }).doneEnd ?? '')
  assert.match(end, /^The identity that requests tokens for directory synchronisation in \{tenant\} is one Conditional Access can cover/)
  // "Creating the policy alone does not establish protection" used to be in both
  // doneEnd and doneWhen; it is one sentence in one place now.
  const done = ((stepById['workload-identity-block'] as unknown as { doneWhen?: string[] }).doneWhen ?? []).join('\n')
  assert.doesNotMatch(end, /Creating the policy alone/)
  assert.match(done, /Creating the policy alone does not establish protection\./)
  assert.equal(checkedOn('s-goal-workload-identity-block'), '2026-09-20')
})
