// The "Control Where People Sign In From" steps, taken to the V1 standard:
// docs/plans/where-people-sign-in-spec.md holds the outcome, the Microsoft Learn
// page behind every technical claim and the date it was checked. The rendered
// words are pinned by docs/qa/step-snapshots; what stays here is the group's
// shape, the lockout instruction and the behaviour behind two of its lines.
//
// A test here reads the OPENED STEP wherever the claim is about what an admin
// sees, and the compiled package block where the claim is about a lifecycle
// state no fixture reaches — the same rule closeDoors.test.ts follows. One step
// of this group (`s-goal-workload-identity-block`) is generated by no fixture at
// all (spec section 9.5), so every claim about it is read from its content entry
// and its package, which are the text its print, export and prompt pack carry.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { stepById } from '../../content/content.ts'
import registry from '../../content/implementation/registry.generated.json' with { type: 'json' }
import { fixture } from '../../roadmap/fixtures/index.ts'
import type { FixtureName } from '../../roadmap/fixtures/index.ts'
import { runFixture } from '../../roadmap/fixtures/run.ts'
import { setDisplayTimeZone } from '../../copy/dates.ts'
import { laneViewOf, prerequisiteLabelFor, readinessBlockersOf, waveStartOf } from './planBoard.ts'
import { laneReadings } from './planLanes.ts'
import { planDates } from './stepVars.ts'
import type { StepVarContext } from './stepVars.ts'
import { objectTaskBodyOf, stepBodyOf } from './stepBody.ts'
import { stepExportView } from './stepExport.ts'
import type { StepBody } from './stepBody.ts'
import { groupOf } from '../../roadmap/stepGroups.ts'

/** The spec's three policy steps (docs/plans/where-people-sign-in-spec.md), in its order. */
const WHERE_SIGN_IN = [
  's-goal-geo-restriction',
  's-goal-service-accounts-trusted-network',
  's-goal-workload-identity-block',
]

/** The two objects a Direction answer asks for, drawn among the objects above the policies (owner, 2026-09-20; roadmap flow section 3). A policy's create waits only on the object it names. */
// The countries location left the objects in Stage 3: it is the countries
// policy's own first task (Step.objectTask), drawn on that step.
const PREPARE_OBJECTS = [
  's-prereq-trusted-location',
  's-prereq-service-accounts-group',
]

/** Every step's body on a fixture, as the Plan composes it (closeDoors.test.ts bodiesOf). */
function bodiesOf(name: FixtureName): Map<string, StepBody> {
  setDisplayTimeZone('UTC')
  try {
    const f = fixture(name)
    const r = runFixture(f, { mapping: f.mapping }, null, f.snapshot.asOf)
    const readings = laneReadings(r.steps, [])
    const titleOf = (id: string): string | null => r.steps.find((s) => s.id === id)?.title ?? null
    const dates = planDates(r.steps, r.schedule.start, r.coverage.organisation.naming, f.snapshot)
    const out = new Map<string, StepBody>()
    for (const step of r.steps) {
      const reading = readings.get(step.id)
      if (!reading) continue
      const lane = laneViewOf(reading, titleOf)
      const ctx: StepVarContext = { snapshot: f.snapshot, mapping: f.mapping, nameOf: (id) => r.input.names!.label(id), signature: 'IT', operatorId: f.operatorId, now: f.snapshot.asOf, ...dates, reportOnlyAt: step.reportOnlyAt ?? null, scheduledOn: waveStartOf(step), groups: f.groups, directory: r.input.directory, naming: r.coverage.organisation.naming }
      out.set(step.id, stepBodyOf(step, ctx, { lane, blockers: readinessBlockersOf(reading, titleOf), prerequisiteLabel: prerequisiteLabelFor(readings) }))
      // The object a step makes itself, as its step draws it (Stage 3: the countries location on the countries step).
      const task = objectTaskBodyOf(step, ctx)
      if (task && step.objectTask) out.set(step.objectTask.id, task)
    }
    return out
  } finally {
    setDisplayTimeZone(null)
  }
}

/** Every string a step's content entry carries, joined: the whole of what it can say. */
function allText(id: string): string {
  const out: string[] = []
  const walk = (n: unknown): void => {
    if (typeof n === 'string') out.push(n)
    else if (Array.isArray(n)) n.forEach(walk)
    else if (n && typeof n === 'object') for (const [k, v] of Object.entries(n)) if (k !== 'example') walk(v)
  }
  walk(stepById[id])
  return out.join('\n')
}

/** A compiled package block's authored text, for a lifecycle state no fixture reaches. */
function blockText(stepId: string, blockId: string): string {
  const pkg = (registry.packages as Record<string, { blocks?: Record<string, { text?: string }> }>)[stepId]
  const text = pkg?.blocks?.[blockId]?.text
  assert.ok(typeof text === 'string' && text !== '', `${stepId}: the package has no ${blockId} block`)
  return text as string
}

// ---------------------------------------------------------------------------
// The group itself
// ---------------------------------------------------------------------------

test('the spec’s three policies close the doors, and the objects they reference are drawn above the policies', () => {
  assert.deepEqual(WHERE_SIGN_IN.map((id) => groupOf(id)?.key), ['remaining-doors', 'remaining-doors', 'remaining-doors'])
  assert.deepEqual(PREPARE_OBJECTS.map((id) => groupOf(id)?.key), ['prepare', 'prepare'])
  // The spec's six steps are five now: the objects drawn above the policies
  // that reference them, and the countries location inside its policy.
  assert.deepEqual([...PREPARE_OBJECTS, ...WHERE_SIGN_IN].sort(), ['s-goal-geo-restriction', 's-goal-service-accounts-trusted-network', 's-goal-workload-identity-block', 's-prereq-service-accounts-group', 's-prereq-trusted-location'])
})

// Left at No, a network condition is not configured and the policy reaches every
// sign-in: for a block that is a lockout. Every network policy of the group says
// Configure: Yes, in its create, its correction and the reviewer's transcription.
test('every network policy sets its condition through Configure: Yes, in create and in correct', () => {
  const cases: [string, string, string, string][] = [
    ['geo-restriction', 's-goal-geo-restriction', 'entra.create', 'entra.correct-conditions'],
    ['service-accounts-trusted-network', 's-goal-service-accounts-trusted-network', 'entra.create', 'entra.correct.network'],
    ['workload-identity-block', 's-goal-workload-identity-block', 'entra.policy.create', 'entra.correct.policy.location-boundary'],
  ]
  for (const [contentId, stepId, create, correct] of cases) {
    assert.match(blockText(stepId, create), /set \*\*Configure\*\* to \*\*Yes\*\*/, `${stepId}: create`)
    assert.match(blockText(stepId, correct), /set \*\*Configure\*\* to \*\*Yes\*\*/, `${stepId}: correct`)
    assert.match(allText(contentId), /Configure: Yes, then Include: Any network or location/, contentId)
  }
  assert.match(blockText('s-goal-geo-restriction', 'entra.create'), /Left at \*\*No\*\* the network condition is not configured/)
  assert.match(blockText('s-goal-service-accounts-trusted-network', 'entra.create'), /Left at \*\*No\*\* the network condition is not configured/)
})

test('T5: the step names every step that waits on it, which the board proves is four', () => {
  const waits = String((stepById['s-prereq-trusted-location'] as unknown as { more?: { waits?: string } }).more?.waits ?? '')
  // The demo's board holds exactly these four waiting on this object.
  const waiting = ['s-shared-devices', 's-goal-register-info-protected', 's-goal-require-managed-device', 's-goal-service-accounts-trusted-network']
  const bodies = bodiesOf('demo')
  for (const id of waiting) {
    const tiles = JSON.stringify(bodies.get(id)!.allTiles)
    assert.match(tiles, /Define the Trusted Network/, `${id}: the board does not show it waiting on the trusted network`)
    assert.ok(waits.includes(bodies.get(id)!.title), `${waits}\n  does not name ${bodies.get(id)!.title}`)
  }
})
