// Prompt 51 Part 1: the content loader and renderer. The renderer is a faithful
// port of docs/design/render-review.py; these tests lock it to the script's own
// output so the words the owner reviews and the words the app renders cannot
// drift, and prove no sentence is invented and no forbidden vocabulary leaks.
//
// The full "every content key is used by a live surface" mapping completes as
// the surfaces are wired (Parts 4-6); here it is asserted against the review
// layer, which renders every step, cleanup entry and page from the file.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { content } from './content.ts'
import { reviewBody } from './render.ts'

// The expectation is render-review.py's own output, regenerated by
// `npm run render-review` and checked in; it lives under docs/qa (not src) so
// the host-allowlist walk over src does not read its Learn links.
const EXPECTED = readFileSync('docs/qa/content-review.expected.html', 'utf8')
const bodyMatch = EXPECTED.match(/<main>([\s\S]*)<\/main>/)
const expectedBody = bodyMatch ? bodyMatch[1] : ''

test('the renderer reproduces render-review.py output exactly (every step, cleanup and page)', () => {
  assert.ok(expectedBody.length > 10000, 'the checked-in expectation is present')
  assert.equal(
    reviewBody(),
    expectedBody,
    'the TypeScript renderer drifted from docs/design/render-review.py — regenerate src/content/review.expected.html with `npm run render-review` and reconcile',
  )
})

test('no rendered sentence carries a forbidden word or a broken value', () => {
  const body = reviewBody()
  const contract = JSON.parse(readFileSync('docs/qa/page-contracts.json', 'utf8')) as { forbidEverywhere: string[] }
  const hits: string[] = []
  // The contract's forbidEverywhere already carries `undefined` and `**`. The
  // tokens are ordinary words, never HTML syntax, so a raw scan of the rendered
  // body is exact. The deliberate {orange} example-gap markers are `{key}`.
  for (const token of contract.forbidEverywhere) {
    if (body.includes(token)) hits.push(token)
  }
  assert.deepEqual(hits, [], `rendered text contains forbidden token(s): ${hits.join(', ')}`)
})

// Every content leaf string that is not surfaced by the review renderer, once
// the structural keys (ids, risk predicates, picker sources) are set aside.
// Each is a string the renderer HAS a code path for but this example's data does
// not trigger (a conditional who-line, a "none recognised" variant) or a page
// string the review page omits but the app surfaces render. A NEW entry here
// means a content string no renderer consumes — a genuine orphan — and fails.
const EXAMPLE_SUPPRESSED_OR_APP_ONLY = [
  '.shared.doesntApplyPrompt',
  '.shared.licenceRule',
  '.pages.home.metaTitle',
  '.pages.connectNoScan.baselineUpdatedNote',
  '.pages.plan.gapSuffix.guests-mfa',
  '.pages.today.activeTip',
  '.pages.today.columns[2]',
  '.pages.today.inventory',
  '.pages.export.unredactedWarning',
  '.pages.how.tip',
  '.steps[1].who.none',
  '.steps[3].decision.location.none',
  '.steps[5].who.none',
  '.steps[5].whatToDo.steps[3]',
  '.steps[6].who.none',
  '.steps[10].who.match',
  '.steps[12].who.groups.noMethod',
  '.steps[12].who.groups.insufficient',
  '.steps[12].who.groups.pushOnly',
  '.steps[12].who.groups.possiblyBroken',
  '.steps[12].who.groups.holdouts',
  '.steps[12].who.adminsNote',
  '.steps[13].who.evidence[1]',
  '.steps[14].who.evidence[1]',
  '.steps[15].who.evidence[0]',
  '.steps[16].who.evidence[1]',
  '.steps[17].who.evidence[0]',
  '.steps[18].who.evidence[0]',
  '.steps[21].who.evidence[2]',
  '.steps[33].who.evidence[0]',
  '.steps[34].who.evidence[1]',
  '.steps[35].who.evidence[0]',
  '.steps[36].who.evidence[0]',
  '.steps[37].who.evidence[0]',
]

const isStructural = (p: string): boolean =>
  /\.id$/.test(p) || /\.applies$/.test(p) || /pickerSource$/.test(p) || /\.kind$/.test(p) || /\.multi$/.test(p) || /\.mergesGoals\b/.test(p) || /\.learn\.(url|cis)$/.test(p)

test('no orphan content string: every non-structural key renders, or is a known example-suppressed / app-only variant', () => {
  const body = reviewBody()
  const escHtml = (s: string): string => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#x27;')
  const leaves: [string, string][] = []
  const walk = (node: unknown, path: string): void => {
    if (typeof node === 'string') {
      leaves.push([path, node])
      return
    }
    if (Array.isArray(node)) {
      node.forEach((v, i) => walk(v, `${path}[${i}]`))
      return
    }
    if (node && typeof node === 'object') {
      for (const [k, v] of Object.entries(node)) {
        if (k === 'example' || k === '$comment' || k === 'version') continue
        walk(v, `${path}.${k}`)
      }
    }
  }
  walk(content, '')
  const miss: string[] = []
  for (const [path, s] of leaves) {
    if (isStructural(path)) continue
    const frags = s.split(/\{[^}]*\}/).map((f) => f.replace(/\s+/g, ' ').trim()).filter((f) => f.length >= 12)
    if (frags.length === 0) continue // a string that is entirely variables
    if (frags.some((f) => body.includes(f) || body.includes(escHtml(f)))) continue
    miss.push(path)
  }
  assert.deepEqual(miss.sort(), [...EXAMPLE_SUPPRESSED_OR_APP_ONLY].sort(), 'the set of non-rendered content strings changed; a new entry is a content key no renderer consumes')
})
