// Inventory (the data as found) and the package-instructions page.
import { count } from './statements.ts'

export const INVENTORY = {
  title: 'Inventory',
  intro: 'Everything the scan read, as found — no analysis. Every table exports to CSV.',
  tabs: {
    policies: 'Policies',
    locations: 'Named locations',
    authentication: 'Authentication',
    people: 'People',
    groups: 'Groups',
    devices: 'Devices',
    roles: 'Roles',
    licensing: 'Licensing',
    apps: 'Apps',
    signIns: 'Sign-in records',
  },
  source: {
    policies: { title: 'Where this comes from', text: 'Conditional Access policies read from the tenant at scan time (/identity/conditionalAccess/policies).' },
    locations: { title: 'Where this comes from', text: 'Named locations read from the tenant (/identity/conditionalAccess/namedLocations). "Used by" counts policies that include or exclude the location.' },
    authentication: { title: 'Where this comes from', text: 'The authentication methods policy, authentication strengths, security defaults, and per-user registration details (/reports/authenticationMethods/userRegistrationDetails).' },
    people: { title: 'Where this comes from', text: 'The user list (/users) with sign-in activity, plus MFA state and strongest method from registered methods and sign-in records.' },
    groups: { title: 'Where this comes from', text: 'Every group any policy includes or excludes, with members read on demand (/groups/{id}/transitiveMembers).' },
    devices: { title: 'Where this comes from', text: 'Registered devices (/devices) with compliance, management, trust type, and registered owners.' },
    roles: { title: 'Where this comes from', text: 'Active role assignments (/roleManagement/directory/roleAssignments) and PIM-eligible schedules where Entra ID P2 is present.' },
    licensing: { title: 'Where this comes from', text: 'Subscribed SKUs (/subscribedSkus) — seats, assigned units, and the service plans that unlock each capability.' },
    apps: { title: 'Where this comes from', text: 'Aggregated app sign-in summary and service principal sign-in activity (/reports, 30 days). Detected workloads drive which goals apply.' },
    signIns: { title: 'Where this comes from', text: 'Counts derived from the interactive sign-in records collected for the window. Raw records stay in the browser and are never shown.' },
  },
  policies: {
    columns: { name: 'Policy', state: 'State', users: 'Users', apps: 'Apps', conditions: 'Conditions', grant: 'Grant', session: 'Session' },
    state: { enabled: 'On', enabledForReportingButNotEnforced: 'Report-only', disabled: 'Off', unknown: 'Unknown' },
    microsoftManaged: 'Microsoft-managed',
    allUsers: 'All users',
    none: 'None',
    groups: (n: number) => count(n, 'group'),
    roles: (n: number) => count(n, 'role'),
    users: (n: number) => count(n, 'user'),
    guests: 'guests',
    allApps: 'All apps',
    office365: 'Office 365',
    adminPortals: 'Admin portals',
    apps: (n: number) => count(n, 'app'),
    userActions: (a: string) => `user action: ${a}`,
    authContexts: (n: number) => count(n, 'auth context'),
    workload: (n: number) => `${count(n, 'service principal')}`,
    clientApps: (s: string) => `client apps: ${s}`,
    platforms: (s: string) => `platforms: ${s}`,
    locations: (s: string) => `locations: ${s}`,
    signInRisk: (s: string) => `sign-in risk: ${s}`,
    userRisk: (s: string) => `user risk: ${s}`,
    flows: (s: string) => `flows: ${s}`,
    deviceFilter: 'device filter',
    block: 'Block',
    require: (s: string) => `Require ${s}`,
    strength: (name: string) => `strength: ${name}`,
    signInFrequency: (h: number) => `sign in every ${h}h`,
    persist: (mode: string) => `browser: ${mode === 'never' ? 'never persist' : 'persist'}`,
    tokenProtection: 'token protection',
    cloudAppSecurity: 'Defender for Cloud Apps',
    appEnforced: 'app-enforced restrictions',
    include: 'Include',
    exclude: 'Exclude',
    empty: 'No Conditional Access policies were read.',
  },
  locations: {
    columns: { name: 'Location', type: 'Type', trusted: 'Trusted', ranges: 'Countries or IP ranges', usedBy: 'Used by' },
    ip: 'IP ranges',
    country: 'Countries',
    trusted: 'trusted',
    notTrusted: 'not trusted',
    usedBy: (n: number) => count(n, 'policy', 'policies'),
    empty: 'No named locations exist yet.',
  },
  authentication: {
    methods: 'Authentication methods policy',
    methodColumns: { method: 'Method', state: 'State', targets: 'Targets' },
    enabled: 'enabled',
    disabled: 'disabled',
    allUsers: 'All users',
    targets: (n: number) => count(n, 'target'),
    strengths: 'Authentication strengths',
    strengthColumns: { name: 'Strength', type: 'Type', combinations: 'Allowed combinations' },
    builtIn: 'built-in',
    custom: 'custom',
    registration: 'Registration statistics',
    regColumns: { measure: 'Measure', users: 'Users' },
    capable: 'MFA-capable',
    registered: 'MFA-registered',
    passwordless: 'Passwordless-capable',
    byMethod: (m: string) => `Registered: ${m}`,
    campaign: 'Registration campaign',
    campaignState: (s: string) => `Campaign: ${s}`,
    securityDefaults: 'Security defaults',
    on: 'on',
    off: 'off',
    migration: (s: string) => `Policy migration: ${s}`,
    empty: 'The authentication methods policy could not be read.',
  },
  people: {
    columns: { name: 'Name', upn: 'Sign-in address', type: 'Type', activity: 'Activity', mfa: 'MFA state', method: 'Strongest method', licence: 'Licence', roles: 'Roles' },
    member: 'member',
    guest: 'guest',
    p2: 'P2',
    p1: 'P1',
    free: 'Free',
    noRoles: '—',
    empty: 'No users were read.',
  },
  groups: {
    columns: { name: 'Group', members: 'Members', dynamic: 'Membership', policies: 'Referenced by' },
    dynamic: 'dynamic',
    assigned: 'assigned',
    unknown: 'unknown',
    sampled: (n: number) => `${n} (sampled)`,
    include: (name: string) => `${name} (include)`,
    exclude: (name: string) => `${name} (exclude)`,
    loading: 'Reading group memberships…',
    empty: 'No policy references a group.',
  },
  devices: {
    columns: { name: 'Device', os: 'OS', trust: 'Trust type', compliant: 'Compliant', managed: 'Managed', lastSignIn: 'Last sign-in', owner: 'Owner' },
    yes: 'yes',
    no: 'no',
    unknown: '—',
    empty: 'No devices are registered.',
  },
  roles: {
    columns: { role: 'Role', active: 'Active holders', eligible: 'Eligible holders' },
    empty: 'No role assignments were read.',
  },
  licensing: {
    columns: { sku: 'Licence', seats: 'Seats', consumed: 'Assigned', capabilities: 'Unlocks' },
    summary: 'Tenant capabilities',
    enabled: 'enabled',
    notLicensed: 'not licensed',
    seats: (enabled: number, consumed: number) => `${enabled} (${consumed} assigned)`,
    none: '—',
    empty: 'No subscribed licences were read.',
  },
  apps: {
    columns: { app: 'App', signIns: 'Sign-ins (30 days)', lastSp: 'Last service principal activity' },
    facets: 'Detected workloads',
    on: 'detected',
    off: 'not detected',
    empty: 'No app sign-in summary is available on this licence.',
  },
  signIns: {
    window: (from: string, to: string, n: number) => `${count(n, 'sign-in')} covering ${from} to ${to}`,
    noWindow: 'No sign-in records were collected.',
    distinctUsers: (n: number) => `${count(n, 'distinct user')}`,
    byClientApp: 'By client app',
    byProtocol: 'By protocol',
    byCountry: 'By country (distinct users)',
    columns: { key: 'Value', count: 'Sign-ins', users: 'Users' },
    deviceCode: 'Device-code flow users',
    authTransfer: 'Authentication transfer users',
    legacy: 'Legacy authentication users',
    blockedToday: 'Blocked today, by policy',
    blockedColumns: { policy: 'Policy', users: 'Users' },
    noPolicy: 'No policy identified',
    nobody: 'nobody',
  },
}

export const PACKAGE = {
  title: 'Baseline packages',
  does: 'What a package is, three ways to make one, and what IAMAI does with it.',
  back: 'Back to Baseline',
  whatTitle: 'What a package is',
  what: [
    'One or more Conditional Access policies as Microsoft Graph JSON (the conditionalAccessPolicy shape).',
    'One policy per file, or an array of policies in one file. Property casing does not matter.',
    'Optional extras: named locations, authentication strengths, and a names lookup — see below.',
  ],
  waysTitle: 'Three ways to make one',
  way1Title: '1. Entra admin center',
  way1: [
    'Entra admin center → Protection → Conditional Access → Policies.',
    'Open a policy, then choose Edit → the "…" menu at the top right → "JSON view".',
    'Click "Download" (or copy the text into a file). Repeat per policy, or use the Overview page\'s "Export" for all policies at once.',
  ],
  way2Title: '2. PowerShell (Microsoft Graph SDK)',
  way2Intro: 'Sign in with a read-only scope, then export each set to a folder:',
  way2Commands: [
    'Connect-MgGraph -Scopes "Policy.Read.All"',
    'Get-MgIdentityConditionalAccessPolicy -All | ConvertTo-Json -Depth 10 | Set-Content .\\package\\policies.json',
    'Get-MgIdentityConditionalAccessNamedLocation -All | ConvertTo-Json -Depth 10 | Set-Content .\\package\\namedLocations.json',
    'Get-MgPolicyAuthenticationStrengthPolicy -All | ConvertTo-Json -Depth 10 | Set-Content .\\package\\authenticationStrengths.json',
  ],
  way3Title: '3. Exports from other tools',
  way3: 'Exports from idPowerToys, CA Policy Copier, DCToolbox, CIPP, or any public GitHub repository of policy JSON load as they are — IAMAI reads the Graph shape all of them produce.',
  bestTitle: 'What to include for best results',
  best: [
    'Named locations — so location conditions resolve to real places instead of ids.',
    'Authentication strengths — so custom strengths resolve to their allowed combinations.',
    'A names lookup (a JSON object of id → display name) — so groups and users referenced by the policies show by name.',
  ],
  missing: 'References that are not included are not a problem: Setup asks about the ones that need a human and resolves the rest from the scan.',
  doesTitle: 'What IAMAI does with the upload',
  doesList: [
    'Reads the files in the browser. Nothing is uploaded anywhere; there is no server.',
    'Normalises each policy to the shape the tenant returns, so one comparison serves both.',
    'Treats every baseline policy as intended-enforced, whatever state it was exported in.',
    'Keeps nothing after the tab closes unless a plan is saved on this device.',
  ],
  copy: 'Copy',
  copied: 'Copied ✓',
  next: 'Next: Baseline',
}
