// Inventory (the data as found) and the package-instructions page.
import { count } from './statements.ts'

export const INVENTORY = {
  title: 'Inventory',
  intro: 'Everything the scan read, as found: no analysis. Every table exports to CSV.',
  tabs: {
    policies: 'Policies',
    locations: 'Named locations',
    authentication: 'Authentication',
    people: 'People',
    groups: 'Groups',
    devices: 'Devices',
    roles: 'Roles',
    licensing: 'Licensing',
    apps: 'Apps',
    signIns: 'Sign-in records',
  },
  source: {
    policies: { title: 'Where this comes from', text: 'Conditional Access policies read from the tenant at scan time (/identity/conditionalAccess/policies).' },
    locations: { title: 'Where this comes from', text: 'Named locations read from the tenant (/identity/conditionalAccess/namedLocations). "Used by" counts policies that include or exclude the location.' },
    authentication: { title: 'Where this comes from', text: 'The authentication methods policy, authentication strengths, security defaults, and per-user registration details (/reports/authenticationMethods/userRegistrationDetails).' },
    people: { title: 'Where this comes from', text: 'The user list (/users) with sign-in activity, plus MFA state and strongest method from registered methods and sign-in records.' },
    groups: { title: 'Where this comes from', text: 'Every group any policy includes or excludes, with members read on demand (/groups/{id}/transitiveMembers).' },
    devices: { title: 'Where this comes from', text: 'Registered devices (/devices) with compliance, management, trust type, and registered owners.' },
    roles: { title: 'Where this comes from', text: 'Active role assignments (/roleManagement/directory/roleAssignments) and PIM-eligible schedules where Entra ID P2 is present.' },
    licensing: { title: 'Where this comes from', text: 'Subscribed SKUs (/subscribedSkus): seats, assigned units, and the service plans that unlock each capability.' },
    apps: { title: 'Where this comes from', text: 'Aggregated app sign-in summary and service principal sign-in activity (/reports, 30 days). Detected workloads drive which goals apply.' },
    signIns: { title: 'Where this comes from', text: 'Counts derived from the interactive sign-in records collected for the window. Raw records stay in the browser and are never shown.' },
  },
  policies: {
    columns: { name: 'Policy', state: 'State', users: 'Users', apps: 'Apps', conditions: 'Conditions', grant: 'Grant', session: 'Session' },
    state: { enabled: 'On', enabledForReportingButNotEnforced: 'Report-only', disabled: 'Off', unknown: 'Unknown' },
    microsoftManaged: 'Microsoft-managed',
    allUsers: 'All users',
    none: 'None',
    groups: (n: number) => count(n, 'group'),
    roles: (n: number) => count(n, 'role'),
    allAdminRoles: (n: number) => `All admin roles (${n})`,
    users: (n: number) => count(n, 'user'),
    guests: 'guests',
    allApps: 'All apps',
    office365: 'Office 365',
    adminPortals: 'Admin portals',
    apps: (n: number) => count(n, 'app'),
    userActions: (a: string) => `user action: ${a}`,
    authContexts: (n: number) => count(n, 'auth context'),
    workload: (n: number) => `${count(n, 'service principal')}`,
    clientApps: (s: string) => `client apps: ${s}`,
    platforms: (s: string) => `platforms: ${s}`,
    locations: (s: string) => `locations: ${s}`,
    signInRisk: (s: string) => `sign-in risk: ${s}`,
    userRisk: (s: string) => `user risk: ${s}`,
    flows: (s: string) => `flows: ${s}`,
    deviceFilter: 'device filter',
    block: 'Block',
    require: (s: string) => `Require ${s}`,
    strength: (name: string) => `strength: ${name}`,
    signInFrequency: (h: number) => `sign in every ${h}h`,
    persist: (mode: string) => `browser: ${mode === 'never' ? 'never persist' : 'persist'}`,
    tokenProtection: 'token protection',
    cloudAppSecurity: 'Defender for Cloud Apps',
    appEnforced: 'app-enforced restrictions',
    include: 'Include',
    exclude: 'Exclude',
    empty: 'No Conditional Access policies were read.',
  },
  locations: {
    columns: { name: 'Location', type: 'Type', trusted: 'Trusted', ranges: 'Countries or IP ranges', usedBy: 'Used by' },
    ip: 'IP ranges',
    country: 'Countries',
    trusted: 'trusted',
    notTrusted: 'not trusted',
    usedBy: (n: number) => count(n, 'policy', 'policies'),
    empty: 'No named locations exist yet.',
  },
  authentication: {
    methods: 'Authentication methods policy',
    methodColumns: { method: 'Method', state: 'State', targets: 'Targets' },
    enabled: 'enabled',
    disabled: 'disabled',
    allUsers: 'All users',
    targets: (n: number) => count(n, 'target'),
    strengths: 'Authentication strengths',
    strengthColumns: { name: 'Strength', type: 'Type', combinations: 'Allowed combinations' },
    builtIn: 'built-in',
    custom: 'custom',
    registration: 'Registration statistics',
    regColumns: { measure: 'Measure', users: 'Users' },
    capable: 'MFA-capable',
    registered: 'MFA-registered',
    passwordless: 'Passwordless-capable',
    byMethod: (m: string) => `Registered: ${m}`,
    campaign: 'Registration campaign',
    campaignState: (s: string) => `Authenticator registration campaign: ${s === 'enabled' ? 'on' : s === 'disabled' ? 'off' : s === 'default' ? 'Microsoft default' : s}`,
    securityDefaults: 'Security defaults',
    on: 'on',
    off: 'off',
    migration: (s: string) => `Policy migration: ${s}`,
    empty: 'The authentication methods policy could not be read.',
  },
  people: {
    columns: { name: 'Name', upn: 'Sign-in address', type: 'Type', activity: 'Activity', mfa: 'MFA state', method: 'Strongest method', licence: 'Licence', roles: 'Roles' },
    member: 'Member',
    guest: 'Guest',
    p2: 'P2',
    p1: 'P1',
    free: 'Free',
    noRoles: '—',
    empty: 'No users were read.',
  },
  groups: {
    columns: { name: 'Group', members: 'Members', dynamic: 'Membership', policies: 'Referenced by' },
    dynamic: 'dynamic',
    assigned: 'assigned',
    unknown: 'unknown',
    sampled: (n: number) => `${n} (sampled)`,
    include: (name: string) => `${name} (include)`,
    exclude: (name: string) => `${name} (exclude)`,
    loading: 'Reading group memberships…',
    empty: 'No policy references a group.',
  },
  devices: {
    columns: { name: 'Device', os: 'OS', trust: 'Trust type', compliant: 'Compliant', managed: 'Managed', lastSignIn: 'Last sign-in', owner: 'Owner', authenticator: 'Authenticator registrations with this device name' },
    yes: 'yes',
    no: 'no',
    unknown: '—',
    empty: 'No devices are registered.',
    sameDevice: {
      title: 'Same device name, likely the same phone',
      text: 'Authenticator registrations carry a device name (a model code such as SM-S918U), not a unique id. Accounts listed here registered Authenticator on a device with the same name as this one: likely the same phone, with medium confidence.',
    },
  },
  roles: {
    usedBy: (holders: string) => `Role used by ${holders}`,
    columns: { role: 'Role', active: 'Active holders', eligible: 'Eligible holders' },
    empty: 'No role assignments were read.',
    showAll: 'Show all roles',
    showHeld: 'Show only roles with holders',
    hiddenNote: (n: number) => `${count(n, 'built-in role')} hidden: no holder, or held only by services.`,
    service: (name: string) => `Service: ${name}`,
    resolving: 'Resolving holder names…',
    privileged: 'privileged',
  },
  licensing: {
    columns: { sku: 'Licence', seats: 'Seats', consumed: 'Assigned', capabilities: 'Unlocks' },
    summary: 'Tenant capabilities',
    enabled: 'enabled',
    notLicensed: 'not licensed',
    seats: (enabled: number, consumed: number) => `${enabled} (${consumed} assigned)`,
    none: '—',
    empty: 'No subscribed licences were read.',
    showZero: 'Show licences with no seats',
    hideZero: 'Hide licences with no seats',
    hiddenZero: (n: number) => `${count(n, 'licence')} with no seats hidden.`,
  },
  apps: {
    columns: { app: 'App', signIns: 'Sign-ins (30 days)', lastSp: 'Last service principal activity' },
    facets: 'Detected workloads',
    on: 'detected',
    off: 'not detected',
    empty: 'No app sign-in summary is available on this licence.',
  },
  signIns: {
    window: (from: string, to: string, n: number) => `${count(n, 'sign-in')} covering ${from} to ${to}`,
    noWindow: 'No sign-in records were collected.',
    distinctUsers: (n: number) => `${count(n, 'distinct user')}`,
    distinctUsersTip: {
      title: 'Distinct users',
      text: 'Users with at least one record inside the collected window (the last 30 days). Readiness counts activity over 90 days, so Active users can be higher than this number.',
    },
    byClientApp: 'By client app',
    byProtocol: 'By protocol',
    byCountry: 'By country (distinct users)',
    columns: { key: 'Value', count: 'Sign-ins', users: 'Users' },
    deviceCode: 'Device-code flow users',
    authTransfer: 'Authentication transfer users',
    legacy: 'Legacy authentication users',
    blockedToday: 'Blocked today, by policy',
    blockedColumns: { policy: 'Policy', users: 'Users' },
    noPolicy: 'No policy identified',
    nobody: 'nobody',
  },
}

export const PACKAGE = {
  title: 'Baseline packages',
  does: 'What a package is, three ways to make one, and what IAMAI does with it.',
  whatTitle: 'What a package is',
  what: [
    'One or more Conditional Access policies as Microsoft Graph JSON (the conditionalAccessPolicy shape).',
    'One policy per file, or an array of policies in one file. Property casing does not matter.',
    'Optional extras, listed below: named locations and authentication strengths.',
  ],
  waysTitle: 'Three ways to make one',
  way1Title: '1. Entra admin center',
  way1: [
    'Entra admin center → Protection → Conditional Access → Policies.',
    'Open a policy, then choose Edit → the "…" menu at the top right → "JSON view".',
    'Click "Download" (or copy the text into a file). Repeat per policy, or use the Overview page\'s "Export" for all policies at once.',
  ],
  way2Title: '2. PowerShell (Microsoft Graph SDK)',
  way2Intro: 'Sign in with a read-only scope, then export each set to a folder:',
  way2Commands: [
    'Connect-MgGraph -Scopes "Policy.Read.All"',
    'Get-MgIdentityConditionalAccessPolicy -All | ConvertTo-Json -Depth 10 | Set-Content .\\package\\policies.json',
    'Get-MgIdentityConditionalAccessNamedLocation -All | ConvertTo-Json -Depth 10 | Set-Content .\\package\\namedLocations.json',
    'Get-MgPolicyAuthenticationStrengthPolicy -All | ConvertTo-Json -Depth 10 | Set-Content .\\package\\authenticationStrengths.json',
  ],
  way3Title: '3. Exports from other tools',
  way3: 'Exports from idPowerToys, CA Policy Copier, DCToolbox, CIPP, or any public GitHub repository of policy JSON load as they are. IAMAI reads the Graph shape all of them produce.',
  bestTitle: 'What to include for best results',
  best: [
    'Named locations: so location conditions resolve to real places instead of ids.',
    'Authentication strengths: so custom strengths resolve to their allowed combinations.',
  ],
  missing: 'References that are not included are not a problem: Setup asks about the ones that need a human and resolves the rest from the scan.',
  doesTitle: 'What IAMAI does with the upload',
  doesList: [
    'Reads the files in the browser. There is no server, and nothing is uploaded: the files are parsed here and stay on this device unless you export them.',
    'Normalises each policy to the shape the tenant returns, so one comparison serves both.',
    'Treats every baseline policy as intended-enforced, whatever state it was exported in.',
    'Keeps nothing after the tab closes unless a plan is saved on this device.',
  ],
  copy: 'Copy',
  copied: 'Copied ✓',
  next: 'Baseline',
}

// ---- Friendly names for Graph enumerations (prompt 19 §B: no raw ids where a human reads) ----
const METHOD_NAMES: Record<string, string> = {
  microsoftauthenticator: 'Microsoft Authenticator',
  microsoftauthenticatorpush: 'Microsoft Authenticator (notification)',
  microsoftauthenticatorpasswordless: 'Microsoft Authenticator (passwordless)',
  fido2: 'Passkey or FIDO2 security key',
  fido2securitykey: 'Passkey or FIDO2 security key',
  passkeydevicebound: 'Passkey (device-bound)',
  passkeydeviceboundauthenticator: 'Passkey in Microsoft Authenticator',
  passkeydeviceboundwindowshello: 'Passkey in Windows Hello',
  windowshelloforbusiness: 'Windows Hello for Business',
  x509certificate: 'Certificate',
  x509certificatemultifactor: 'Certificate (multifactor)',
  x509certificatesinglefactor: 'Certificate (single factor)',
  temporaryaccesspass: 'Temporary Access Pass',
  softwareoath: 'Authenticator app code (software)',
  softwareonetimepasscode: 'Authenticator app code (software)',
  hardwareoath: 'Hardware token code',
  hardwareonetimepasscode: 'Hardware token code',
  sms: 'Text message',
  voice: 'Phone call',
  mobilephone: 'Text or call (mobile)',
  alternatemobilephone: 'Text or call (alternate mobile)',
  officephone: 'Phone call (office)',
  email: 'Email (self-service password reset only)',
  securityquestion: 'Security questions (self-service password reset only)',
  federatedsinglefactor: 'Federated sign-in (single factor)',
  federatedmultifactor: 'Federated sign-in (multifactor)',
  password: 'Password',
  deviceboundpasskey: 'Passkey (device-bound)',
  qrcodepin: 'QR code and PIN',
  externalauthenticationmethod: 'External authentication method',
  devicebasedpush: 'Microsoft Authenticator (device-based push)',
  temporaryaccesspassonetime: 'Temporary Access Pass (one-time)',
  temporaryaccesspassmultiuse: 'Temporary Access Pass (multi-use)',
  verifiablecredentials: 'Verified ID credentials',
  phoneappnotification: 'Microsoft Authenticator (notification)',
  phoneappotp: 'Microsoft Authenticator (code)',
  onewaysms: 'Text message',
  twowayvoicemobile: 'Phone call',
  twowayvoiceoffice: 'Phone call (office)',
  fido2securitykeys: 'Passkey or FIDO2 security key',
  hardwareoathtoken: 'Hardware token code',
  softwareoathtoken: 'Authenticator app code (software)',
  passwordlessmicrosoftauthenticator: 'Microsoft Authenticator (passwordless)',
}
export function methodName(id: string): string {
  return METHOD_NAMES[id.toLowerCase()] ?? id
}
/** A comma-separated combination such as "fido2" or "microsoftAuthenticatorPush,federatedSingleFactor". */
export function combinationName(combo: string): string {
  return combo.split(',').map((part) => methodName(part.trim())).join(' + ')
}
const MIGRATION_NAMES: Record<string, string> = {
  premigration: 'not started (legacy MFA and SSPR settings still apply)',
  migrationinprogress: 'in progress (legacy settings still apply)',
  migrationcomplete: 'complete (this policy is authoritative)',
}
export function migrationName(state: string): string {
  return MIGRATION_NAMES[state.toLowerCase()] ?? state
}
const PROTOCOL_NAMES: Record<string, string> = {
  none: 'Standard sign-in',
  ropc: 'Username and password in the app (ROPC)',
  devicecode: 'Device-code flow',
  authenticationtransfer: 'Authentication transfer',
  samlassertion: 'SAML assertion',
  encryptedauthorize: 'Encrypted authorise',
  jwtbearer: 'Token exchange (JWT bearer)',
  refreshtoken: 'Refresh token',
  unknownfuturevalue: 'Other',
}
export function protocolName(p: string): string {
  return PROTOCOL_NAMES[p.toLowerCase()] ?? p
}
const TRUST_NAMES: Record<string, string> = {
  azuread: 'Entra joined',
  serverad: 'Hybrid joined',
  workplace: 'Entra registered',
}
export function trustTypeName(t: string): string {
  return TRUST_NAMES[t.toLowerCase()] ?? t
}
