// Page copy. Voice: IAMAI is the subject, or the sentence is imperative. No
// first person, no reassurance adjectives, no developer vocabulary.
import { lowerFirst } from './statements.ts'
import { count } from './statements.ts'

export const SHELL = {
  wordmark: 'IAMAI',
  tagline: 'Conditional Access rollout planner for Microsoft Entra ID and Microsoft 365',
  tenantTooltip: (tenantId: string, username: string) => `Tenant ID ${tenantId} · signed in as ${username}`,
  lightTheme: 'Light theme',
  darkTheme: 'Dark theme',
  themeTooltip: 'Switch between dark and light themes',
  themeState: (theme: string) => `Theme: ${theme}. Switch to ${theme === 'dark' ? 'light' : 'dark'}`,
  forget: 'Forget this tenant',
  // The header (prompt 47 Part 3, target-state §2).
  navLabel: 'Sections',
  tabs: { today: 'Today', plan: 'Plan', export: 'Export' },
  tabsAfterScan: 'after the first scan',
  /** "Re-scan · scanned 24h ago": the age in the fewest characters, as target-state §2 writes it. */
  rescanScanned: (age: { hours: number; days: number }) =>
    `Re-scan · scanned ${age.hours < 1 ? 'just now' : age.hours < 48 ? `${age.hours}h ago` : `${age.days}d ago`}`,
  recovery: 'Recovery card',
  account: 'Account',
  accountTooltip: (username: string) => `Signed in as ${username}`,
  signOut: 'Sign out',
  /** The demo banner (prompt 45 Part 1). Persistent, and one click to leave. */
  demoBanner: 'Sample data. Nothing here is from a real tenant.',
  demoLeave: 'Leave the demo',
  demoWatermark: 'SAMPLE DATA. Generated by IAMAI demo mode from a built-in sample tenant. Nothing in this file came from a real Microsoft 365 tenant.',
  // Error boundary (prompt 20 §2)
  errorTitle: 'This page hit an error',
  errorCalloutTitle: 'Nothing in the tenant changed',
  errorBody:
    'The page could not finish drawing. The saved scan, Setup answers and plan on this device are intact. Download the diagnostics to report the problem, or start over from the Start step.',
  errorDiagnostics: 'Download diagnostics (redacted)',
  errorStartOver: 'Start over',
  errorDetail: (message: string) => `Technical detail: ${message}`,
  // Scan age (prompt 20 §9)
  basedOn: (when: string) => `Based on the scan from ${when}.`,
  rescan: 'Re-scan',
  baselineLoaded: (source: string) => `Baseline: ${source}`,
  scanAgeTip: 'Scan age',
  evidenceAgeNote: 'Sign-in evidence covers the last 30 days; re-scan once the scan is more than 7 days old.',
  scanStale: (days: number) => `This scan is ${days} days old. Numbers, names and sign-in evidence may have moved on.`,
  scanStaleAction: 'Re-scan the tenant',
  forgetTooltip: 'Deletes everything IAMAI stored for this tenant on this device, then signs out',
  printHeader: (tenant: string, date: string, by: string) => `IAMAI plan for ${tenant} · prepared ${date} by ${by}`,
  // "Nothing leaves your browser" was absolute, and the product's own
  // headline features exist to move data out when the user asks (audit
  // egress-05). What is true without qualification is that nothing goes
  // anywhere on its own.
  footerLeft: 'Read-only · nothing is sent automatically',
  footerFollow: 'Follow me here:',
  footerAuthor: 'Lachlan Robinette',
  footerHome: 'All IAMAI tools',
  /**
   * The build stamp (prompt 40 §24). Two branches: a real commit links to it,
   * and a local build says so rather than linking to a commit that does not
   * exist on the remote. The date is spelled out because a raw ISO date is
   * developer vocabulary everywhere else in the product.
   */
  footerBuild: (commit: string, date: string) => (commit === 'dev' ? `Local build, ${date}` : `Build ${commit}, ${date}`),
  footerBuildTitle: 'The commit this page was built from',
  footerGithub: 'GitHub',
  footerSource: 'Source',
  needs: 'Needs:',
  next: (label: string) => `Next: ${label}`,
  steps: {
    start: 'Start',
    connect: 'Connect',
    baseline: 'Baseline',
    scan: 'Scan',
    mapping: 'Setup',
    coverage: 'Findings',
    roadmap: 'Roadmap',
    licensing: 'Licensing guide',
    reads: 'What IAMAI reads',
    checks: 'Every check IAMAI runs',
    naming: 'Naming policies and groups',
    recovery: 'Recovery card',
    inventory: 'Inventory',
    prompts: 'Prompt pack',
  },
  loading: 'Loading…',
  signInError: 'Sign-in error:',
  storageBlocked: 'Saved data is not available yet',
  scanNeedsConnect: 'The scan reads the tenant into a local record. Connect a tenant first.',
  connectLink: 'Connect a tenant',
  inventoryNeedsConnect: 'The inventory comes from a scan of a connected tenant. Connect a tenant first.',
}

export const START = {
  // C1: the visitor has a tenant and a fear, not a baseline. The old headline
  // opened on a word they have no reason to know and asked them to turn one
  // thing they do not have into another. It says what they get now, and
  // "baseline" waits until the page has explained it.
  headline: 'Know what a Conditional Access change will do before you make it.',
  subhead:
    "IAMAI reads your Microsoft 365 tenant and tells you who each change locks out, what order to make them in, and what to watch afterwards.",
  caveat: 'Predicted impact, confirmed in report-only.',
  cta: 'Get started',
  demoNote: 'No sign-in, and nothing read from any tenant. A sample tenant, walked end to end.',
  howTitle: 'How it works',
  how: [
    { icon: 'shield', title: 'Connect', text: 'One sign-in, one consent screen, on the tenant you already administer.' },
    { icon: 'policy', title: 'Choose a baseline', text: 'Start from a maintained policy set, or upload a package.' },
    { icon: 'chart', title: 'Scan and see readiness', text: 'Who could pass MFA today, who needs a hand, and who is blocked right now: by name.' },
    { icon: 'check', title: 'Follow the roadmap', text: 'Waves with dates, the changes that are safe today, and what to watch first.' },
  ] as const,
  needTitle: "What you'll need",
  need: [
    'A Microsoft 365 tenant with Microsoft Entra ID (any licence). A Global Administrator or Global Reader account.',
    'Entra ID P1 for sign-in records. IAMAI works without it, with less evidence.',
    'About ten minutes for the first scan.',
  ],
  readsTitle: 'What IAMAI reads, and why',
  reads: [
    'The Conditional Access configuration: to compare it with the baseline.',
    'User, device, and licence inventory: to size every step\'s impact.',
    'Recent interactive sign-in records: to check that MFA works before anything is enforced.',
  ],
  readsLink: 'The full list, with every endpoint and permission →',
  neverTitle: 'What IAMAI never does',
  never: [
    'No changes to the tenant: the app holds read-only permissions only.',
    'No tenant data is sent anywhere on its own. There is no server, no analytics and no telemetry.',
    'What you export moves when you choose it: saving a plan or a CSV, copying a prompt, printing, or emailing feedback.',
    'No account required with anyone.',
  ],
  sourceBefore: '',
  sourceLink: 'The source is public',
  sourceAfter: ', so every claim above can be checked.',
}

export const CONNECT = {
  title: 'Connect',
  does: "Signs in read-only so IAMAI can read the tenant's configuration and inventory.",
  needs: 'a Global Administrator or Global Reader account',
  next: 'Baseline',
  signedInTo: 'Signed in to',
  as: 'as',
  tenantId: 'Tenant ID',
  savedScan: (when: string, users: number | null) =>
    `A scan from ${when}${users ? ` (${count(users, 'user')})` : ''} is saved on this device: go straight to`,
  findings: 'Findings',
  or: 'or',
  roadmap: 'Roadmap',
  signOut: 'Sign out',
  bullets: [
    // "IAMAI is read-only. It never creates, edits, or deletes anything in the
    // tenant." was here and said the same thing as the lead sentence above it
    // (review-07 R20, prompt 40 §23). The claim is made once, in the lead, and
    // the permissions disclosure carries the evidence for it.
    'Admin consent creates an enterprise app named IAMAI in the tenant. To remove all access later, delete that enterprise app: nothing else is left behind.',
  ],
  sourceBefore: '',
  sourceLink: 'The source is public',
  sourceAfter: ', so every claim above can be checked.',
  signIn: 'Sign in with Microsoft',
  signInOpening: 'Opening the Microsoft sign-in…',
  readOnlyTip: {
    title: 'Not even report-only',
    text: 'A report-only policy is a Conditional Access policy that only records what it would have done. IAMAI never creates one either: the plan asks you to create each policy yourself.',
  },
}

/** Branches: none, all required, none required, some required (prompt 19 §A2). */
function BASELINE_QUESTIONS({ total, required }: { total: number; required: number }): string {
  if (total === 0) return 'Setup has nothing to ask'
  if (required === total) return `Setup will ask ${count(total, 'question')} (all required)`
  if (required === 0) return `Setup will ask ${count(total, 'question')} (none required)`
  return `Setup will ask ${count(total, 'question')} (${required} required)`
}

export const BASELINE = {
  title: 'Baseline',
  does: 'Picks the target policy set the rollout plan aims for.',
  next: 'Scan',
  fetching: (n: number) => `Fetching ${count(n, 'file')} from GitHub at the pinned commit…`,
  readingProgress: (done: number, total: number) => `Reading ${done} of ${total} files…`,
  reading: (n: number) => `Reading ${count(n, 'uploaded file')}…`,
  uploadedSource: (n: number) => `uploaded package (${count(n, 'file')})`,
  load: 'Load this baseline',
  orUpload: 'or upload a package',
  howToPackage: 'how to make one',
  loadFailed: 'Load failed.',
  // C7: the page never said what a baseline is. Two sentences, before anything
  // else, because everything below assumes the reader already knows.
  whatIsIt: [
    'A baseline is a set of Conditional Access policies somebody has already worked out and maintains: what to require, of whom, and in what order.',
    'IAMAI compares this tenant against one and builds the plan from the difference, so the target is a published policy set rather than an opinion.',
  ],
  aboutTitle: 'About this baseline',
  by: 'by',
  /** C7: who maintains it, and why that is worth knowing. */
  credential: 'Microsoft MVP in identity and access',
  /** C7: a pinned copy ages; say when it was taken and what to do about it. */
  freshness: (date: string) => `This copy was captured ${date}. Reloading it every month or so picks up changes to the source.`,
  repository: 'repository',
  capturedOn: (date: string) => `Captured ${date}`,
  commit: (c: string) => `version ${c.slice(0, 7)}`,
  noDescription: 'No description provided.',
  filesIn: (files: number, policies: number | null) => (policies === null ? `${count(files, 'file')} in this baseline` : `${count(files, 'file')}, ${count(policies, 'usable policy', 'usable policies')}`),
  targets: (tiers: string) => `targets ${tiers}`,
  loadedTitle: (source: string) => `Loaded: ${source}`,
  restoreFailed: 'The baseline saved with the scan could not be restored. Load it again below.',
  uploadLabel: 'Upload baseline policy files',
  summaryLine: (policies: number, goals: number, questions: { total: number; required: number }) =>
    `${count(policies, 'policy', 'policies')} · ${count(goals, 'security goal')} in this baseline (Findings shows how many apply to the tenant) · ${BASELINE_QUESTIONS(questions)}`,
  authorNote: 'For the baseline author: these lines describe the export, not this tenant.',
  policiesReady: (n: number) => `${count(n, 'policy', 'policies')} ready to compare.`,
  unusable: (n: number) =>
    `${count(n, 'policy', 'policies')} in the source cannot be used yet (exported without targets): this does not affect the plan.`,
  choices: (n: number) => `${count(n, 'choice')} to make in Setup (${n === 1 ? 'two styles of the same policy' : 'alternative styles of the same policies'}).`,
  references: (n: number) => `${count(n, 'reference')} to the tenant. Setup resolves the ones that need a human; the rest are automatic.`,
  technical: 'Technical details',
  considered: (considered: number, parsed: number) => `${count(considered, 'file')} considered, ${parsed} parsed cleanly.`,
  duplicates: (n: number) => `${count(n, 'duplicate pair')} collapsed.`,
  parseErrors: (n: number, paths: string) => `${count(n, 'file')} failed to parse and ${n === 1 ? 'was' : 'were'} skipped: ${paths}`,
  unusableList: (names: string) => `Exported without their targets (the people they apply to were lost in the export), so they cannot be compared: ${names}`,
  fetchFailures: (n: number) => `${count(n, 'file')} could not be fetched from the source repository.`,
  labState: 'Baseline policy states are the author\'s lab state; every baseline policy is treated as intended-enforced unless a manifest says otherwise.',
}

export const SCAN = {
  title: 'Scan',
  does: "Reads the tenant's configuration, inventory, and sign-in records into a local record on this device.",
  needs: 'connected tenant',
  next: 'Setup',
  scan: 'Scan tenant',
  rescan: 'Re-scan tenant',
  failed: 'Scan failed.',
  sessionExpired: 'Your Microsoft session expired. Sign in again to continue.',
  sessionExpiredBody: 'The scan is paused where it got to; nothing collected so far is lost.',
  signInAgain: 'Sign in again',
  usingSaved: (when: string) => `Scan completed ${when} · saved on this device. Re-scan any time for fresh numbers.`,
  slow: "Microsoft's sign-in record service is slow right now: this can take several minutes on larger tenants. Everything else is already collected.",
  details: 'Details',
  reading: 'reading…',
  found: (label: string, n: number) => `${label}: ${n.toLocaleString('en')}`,
  sectionsBar: (done: number, total: number) => `Configuration and inventory · ${done} of ${total}`,
  signInsBar: (rows: number, oldest: string | null) => `Sign-in records · ${rows} read${oldest ? ` · covered back to ${oldest}` : ''}`,
  waitingFirstBatch: 'Sign-in records · waiting for the first batch from Microsoft (about a minute)',
  nowReading: (labels: string[]) => (labels.length > 0 ? `Now reading: ${labels.join(', ')}…` : 'Finishing up…'),
  elapsed: (t: string) => `${t} elapsed`,
  completeLine: (users: number, policies: number, window: string | null) =>
    `${count(users, 'user')} · ${count(policies, 'policy', 'policies')} · ${window ? `sign-in records for ${window}` : 'no sign-in records'}`,
  tabs: { readiness: 'Readiness', inventory: 'Inventory' },
  readiness: 'Readiness',
  signInRecords: 'Sign-in records:',
  complete: 'complete',
  evidenceStatus: {
    ok: 'complete',
    partial: 'partly collected',
    insufficient: 'too few to use',
    disabled: 'not available on this licence',
    error: 'could not be read',
    pending: 'not collected yet',
    started: 'reading…',
  } as Record<string, string>,
  covering: (from: string, to: string) => `covering ${from} to ${to}`,
  pending: 'Sign-in records have not been collected yet; states below are based on registered methods only',
  unusable: 'States below are based on registered methods only; nothing can be Verified without usable records',
  mfaState: 'MFA state',
  activity: 'Activity',
  rollout: 'Rollout',
  blockedToday: (n: number) => `Blocked today: ${count(n, 'user')} whose most recent sign-in failed Conditional Access.`,
  noPolicyIdentified: 'No policy identified',
  users: (n: number) => `${count(n, 'user')}`,
  search: 'Search name or sign-in address…',
  searchLabel: 'Search users',
  clearFilters: 'Clear filters',
  noMatch: 'No users match these filters.',
  legend: 'Legend',
  /** "12 · 40%": count first, share of enabled users second (ux-review-04 §1). */
  rolloutValue: (n: number, enabled: number) => (enabled === 0 ? '0' : `${n.toLocaleString('en')} · ${Math.round((n / enabled) * 100)}%`),
  columns: {
    user: 'User',
    signInAddress: 'Sign-in address',
    admin: 'Admin',
    activity: 'Activity',
    mfa: 'MFA state',
    method: 'Strongest method',
    reasons: 'Reasons',
    care: 'Handle with care',
  },
  yes: 'yes',
  guest: 'Guest',
  care: 'care',
  createdAgo: (rel: string) => `created ${rel}`,
  mfaVia: (method: string, rel: string) => `MFA via ${method} ${rel}`,
  mfaCompleted: (rel: string) => `MFA completed ${rel}`,
  authenticatorStale: 'Authenticator app out of date',
  authenticatorCurrent: 'Authenticator app up to date',
  sections: {
    'config:caPolicies': 'Conditional Access policies',
    'config:namedLocations': 'Named locations',
    'config:authStrengths': 'Authentication strengths',
    'config:authMethodsPolicy': 'Authentication methods policy',
    'config:securityDefaults': 'Security defaults',
    'config:crossTenantAccess': 'Cross-tenant access',
    'config:roleAssignments': 'Role assignments',
    'config:pimEligibility': 'PIM eligibility',
    'config:subscribedSkus': 'Licences',
    'config:organization': 'Organisation',
    'config:me': 'The signed-in account',
    'config:meMemberOf': 'Its groups',
    registrationDetails: 'MFA registration',
    users: 'People',
    devices: 'Devices',
    spActivity: 'Service principal activity',
    authMethods: 'Registered methods',
    appSignInSummary: 'App usage',
    signInEvidence: 'Sign-in records',
  } as Record<string, string>,
}

export const FINDINGS = {
  title: 'Findings',
  does: 'What the scan found in the tenant.',
  noScanTitle: 'No scan yet',
  next: 'Roadmap',
  needsScan: 'scan complete',
  needScan: 'Run a scan in the Scan step',
  needsBaseline: 'baseline loaded',
  needBaseline: 'Load a baseline in the Baseline step',
  blocked: 'Findings need a scan.',
  runScan: 'Run a scan',
  and: 'and',
  loadBaseline: 'load a baseline',
  resolving: 'Reading group memberships…',
  basedOn: (when: string) => `Based on the scan from ${when}.`,
  rescan: 'Re-scan',
  // C4: every other tab strip in the app is nouns; these two were sentences.
  tabs: { summary: 'Summary', working: 'In place', attention: 'Needs attention', details: 'Details' },
  sinceCheckpoint: (when: string) => `Since the last checkpoint (${when}):`,
  tiles: { inPlace: 'In place', partly: 'Partly', missing: 'Missing', scored: 'of scored goals in place', proven: 'of enabled users proved MFA in the last 30 days', toSetUp: 'enabled users to set up before enforcement' },
  nothingInPlace: 'Nothing is fully in place yet: that is what the plan is for.',
  allInPlace: 'Everything the baseline asks for is in place. Re-scan periodically; drift is flagged.',
  policiesInvolved: 'Policies involved',
  reportOnly: 'report-only',
  delivers: 'delivers it',
  tooWeak: 'applies but too weak',
  disabledCandidate: 'switched off',
  whyNot: 'Why not fully',
  expected: '(expected)',
  usersCount: (n: number) => `${count(n, 'user')}`,
  seeStep: 'See the step for this in the Roadmap →',
  // Control bar and badges (prompt 17 §2)
  groupBy: 'Group by',
  sortBy: 'Sort by',
  groupNone: 'None',
  groupDomain: 'Domain',
  sort: { priority: 'Priority', value: 'Security value', effort: 'Effort', disruption: 'Disruption' } as Record<string, string>,
  /**
   * Where a goal that came from the baseline rather than the catalogue is
   * filed (prompt 37 §12). It used to fall back to Identity, which is how a
   * download-restriction session control came to sit under Identity (T16).
   * A goal IAMAI cannot classify is better shown as unclassified than filed
   * under a heading that is wrong.
   */
  otherDomain: 'Other goals from your baseline',
  whyMatters: 'Why this matters',
  proposedName: 'Proposed name:',
  // Both numbers are over the goals IAMAI evaluated, so "the rest" is exactly
  // what Details holds. The first used to count matched goals in the baseline
  // package instead, a different set, which let the second exceed it (T3).
  goalCounts: (considered: number, apply: number) =>
    considered === apply
      ? `${count(considered, 'goal')} considered; every one applies to this tenant.`
      : `${count(considered, 'goal')} considered, ${apply} apply to this tenant. The rest are under Details with the reason each one does not apply.`,
  howToFix: 'How to fix this',
  fixText: (goal: string) => `The Roadmap has a dated step for "${goal}" with the exact change, who it touches, and what to check before enforcing.`,
  fixLink: 'Open the step',
  badge: { value: 'Value', effort: 'Effort', disruption: 'Disruption' },
  learn: 'Microsoft Learn →',
  cis: (c: string) => `CIS ${c}`,
  notInScope: 'Not in scope for this tenant',
  couldNotEvaluate: 'Could not be evaluated',
  notInBaseline: 'Policies not in the baseline',
  everyPolicyMaps: 'Every policy maps to a goal.',
  fineToKeep: 'fine to keep; not part of this baseline',
  organisationTitle: 'How this tenant is organised',
  organisationLead: 'Not security findings, and not part of the score. This is how the policies are arranged: names, duplicates, and the ones nobody has looked at in a while.',
  organisationNone: 'Nothing to tidy: the policies are named consistently, none duplicate another, and none has been left in report-only or disabled.',
  organisationWhat: 'What',
  organisationWhy: 'Why it matters here',
  organisationChange: 'The change',
  housekeeping: 'Housekeeping',
  naming: (share: number, pattern: string, outliers: string) =>
    `Naming: ${share}% of the policies share the prefix "${pattern}"${outliers ? `; outliers: ${outliers}` : ''}`,
  /** Policies with no prefix at all, which is what makes a list of forty unreadable. */
  unprefixed: (n: number, names: string) =>
    `${n === 1 ? 'One policy carries' : `${n} policies carry`} no prefix at all, which is what makes a long list hard to read: ${names}.`,
  noNaming: "Naming: no dominant naming convention yet: the plan uses the baseline's",
  consolidate: (goal: string, n: number) => `${goal} is delivered by ${count(n, 'policy', 'policies')}: consider consolidating`,
  microsoftManaged: (list: string) => `Microsoft-managed policies: ${list}`,
  delta: {
    goals: (from: number, to: number) => `goals in place ${from} → ${to}`,
    verified: (n: number, more: boolean) => `${n} ${more ? 'more' : 'fewer'} verified ${n === 1 ? 'user' : 'users'}`,
    noMethod: (n: number, fewer: boolean) => `${n} ${fewer ? 'fewer' : 'more'} without a method`,
    regressed: (n: number) => `${count(n, 'goal')} regressed: check for policy changes outside the plan`,
    nothing: 'nothing has changed.',
  },
}

export const ROADMAP = {
  title: 'Roadmap',
  does: 'Your plan: what to change, in what order, and what to watch.',
  needsScan: 'scan complete',
  needScan: 'Run a scan in the Scan step',
  needsBaseline: 'baseline loaded',
  needBaseline: 'Load a baseline in the Baseline step',
  preparing: 'Preparing the plan (reading group memberships)…',
  blocked: 'The plan builds from a scan and a baseline.',
  runScan: 'Run a scan',
  and: 'and',
  loadBaseline: 'load a baseline',
  basedOn: (when: string) => `Based on the scan from ${when}.`,
  rescan: 'Re-scan',
  tabs: { progress: 'Progress', plan: 'Plan', danger: 'Watch first', schedule: 'Schedule', export: 'Export' },
  weeksBadge: (w: number) => `${w}w`,
  // Overview redesign (prompt 26 §6-§9)
  headline: (done: number, total: number, finishes: string) => `${done} of ${total} steps in place · finishes ${finishes}`,
  headlineDone: (total: number) => `All ${count(total, 'step')} in place`,
  consolidationLead: (n: number) => `${count(n, 'consolidation candidate')}:`,
  readyToday: 'Ready today',
  attentionTitle: 'What needs attention before you start',
  nothingToWatchTitle: 'Nothing needs attention',
  nothingToWatchText: 'Nobody is blocked today and no step is waiting on anything. Start with the first step in the plan.',
  noPlanTitle: 'No plan yet',
  noDangersTitle: 'Nothing to watch first',
  attentionDangers: (n: number) => (n === 0 ? 'Nothing to watch first: nobody is blocked today.' : `${count(n, 'thing')} to watch before anything is enforced.`),
  attentionBlocked: (n: number) => (n === 0 ? 'Nothing is blocked.' : `${count(n, 'step')} blocked; each one names what unblocks it.`),
  openDangers: 'Open Watch first →',
  openBlocked: 'See the blocked steps →',
  settingsTitle: 'Plan settings',
  overrunShow: (n: number) => `${count(n, 'step')} run past the campaign: show`,
  phaseProgress: (done: number, total: number) => `${done} of ${count(total, 'step')} done`,
  phaseAllDone: (n: number) => `${n} done`,
  minimapToday: 'Today',
  /** Short labels for the mini-map, where the full window title will not fit (prompt 40 §19). */
  minimapRegistration: 'Registration',
  minimapObservation: 'Observation',
  windowChip: 'Waiting period',
  collapseStep: 'Collapse',
  stepsBadge: (done: number, total: number) => `${done}/${total} steps done`,
  paceLabel: 'Pace:',
  // Size bands (§A3): the pace follows the tenant; the band can be overridden.
  bands: {
    small: { label: 'Small', text: 'Up to 30 active users: about 4 weeks, with a 2-week registration and verification window.' },
    mid: { label: 'Mid', text: '31 to 300 active users: about 8 weeks, with a 4-week registration and verification window.' },
    large: { label: 'Large', text: 'More than 300 active users: about 12 weeks, with a 6-week registration and verification window.' },
  } as Record<string, { label: string; text: string }>,
  bandWord: { small: 'small-tenant', mid: 'mid-size', large: 'large-tenant' } as Record<string, string>,
  bandAuto: (active: number, label: string) => `${count(active, 'active user')}: ${label} band, detected`,
  bandOverride: (active: number, label: string) => `${count(active, 'active user')}: ${label} band, your choice`,
  bandReset: 'Back to detected',
  expected: (weeks: number) => `this pace usually takes ${count(weeks, 'week')}`,
  verificationWindow: (days: number) => `Registration and verification window · ${days} days`,
  verificationText: (toSetUp: number, active: number) =>
    toSetUp === 0
      ? 'Nobody needs setting up: the window is skipped.'
      : `${count(toSetUp, 'user')} still ${toSetUp === 1 ? 'needs' : 'need'} setting up (${count(active, 'active user')} in total): each registers Microsoft Authenticator and completes one MFA sign-in; re-scans track it.`,
  verificationDone: 'Verification complete: the window is skipped and the waves pull forward.',
  showCompleted: 'Show completed',
  hideCompleted: 'Hide completed',
  completedHidden: (n: number) => `${count(n, 'completed step')} hidden`,
  day0: 'Day 0',
  day0Text: (n: number) => `The ${n === 1 ? 'new policy starts' : `${n} new policies start`} in report-only, where ${n === 1 ? 'it affects' : 'they affect'} nobody.`,
  observation: (days: number) => `Observation window · ${days} days`,
  observationText: 'Every new policy collects report-only evidence at the same time.',
  wave: (n: number, name: string) => `Wave ${n} · ${name}`,
  /**
   * A wave is named by the goals it holds, in phase order, never by one
   * dominant phase. "Wave 1 · Devices" held admin portals, guest MFA, geo
   * blocking, privileged-role activation and session controls (review-08 B6,
   * prompt 40 §20). Four branches, because a wave can hold any number of areas:
   * none (it is empty and is not drawn), one, two, or more than two.
   */
  waveAreas: (names: string[]): string =>
    names.length === 0
      ? 'No goals'
      : names.length === 1
        ? names[0]
        : names.length === 2
          ? `${names[0]} and ${names[1]}`
          : `${names[0]}, ${names[1]} and ${names.length - 2} more`,
  blockedBy: 'Blocked until',
  // The lead is short because the items it introduces are whole clauses and the
  // sentence has a 25-word budget (target-state §8.7).
  dangerLead: (titles: string[]) =>
    titles.length === 1
      ? `Before the plan starts, one thing to look at: ${lowerFirst(titles[0])}.`
      : `Before the plan starts, look at: ${titles.slice(0, 3).map(lowerFirst).join('; ')}${titles.length > 3 ? `; and ${titles.length - 3} more` : ''}.`,
  showRoles: (n: number) => `Show the ${count(n, 'role')}`,
  whyLink: 'Reference from the baseline author →',
  setupQuestionLink: (n: number) => `Setup question ${n}`,
  sortBy: 'Sort by',
  sortSchedule: 'Schedule',
  currentScope: 'Today the policy targets',
  safeToday: (n: number) => `Safe today (${n}):`,
  safeTodayWhy: (tenant: string) => `Nobody in ${tenant} used what these block in the last 30 days, so enforcing them is predicted to interrupt no one.`,
  dangers: (high: number) => `${count(high, 'thing needs', 'things need')} care before the plan starts:`,
  dangersAfter: 'the Watch first tab names the people and the exact settings.',
  dangersMedium: (n: number) => `${count(n, 'area')} to watch, none urgent: the Watch first tab names the people.`,
  lastStep: 'This is the last step. Re-scan after each change to update progress.',
  rescanProgress: 'Re-scan to update progress',
  blockedSteps: (n: number) =>
    `${count(n, 'step is', 'steps are')} blocked right now; each one says exactly what unblocks it. Most clear once the verification campaign in phase 2 lands.`,
  startDate: 'Plan start date:',
  save: 'Save plan',
  copyMarkdown: 'Copy as Markdown',
  copied: 'Copied ✓',
  load: 'Load plan',
  print: 'Print the plan',
  couldNotRead: 'could not read the plan file',
  // A plan carries one tenant's policy ids, group ids and operator notes, and
  // the filename is only eight characters of a tenant id. Loading it into
  // another tenant put one client's identifiers into another client's change
  // record (audit token-01). Both are named so the operator can see which file
  // they picked; the id itself is never shown.
  planFromAnotherTenant: (planTenant: string, current: string) =>
    `This plan was made for ${planTenant || 'another tenant'}, and you are connected to ${current || 'a different tenant'}. Nothing was loaded. Open it while connected to ${planTenant || 'the tenant it was made for'}.`,
  planTenantUnknown: (current: string) =>
    `This plan file does not say which tenant it was made for, so it cannot be loaded into ${current || 'this tenant'} safely. Nothing was loaded.`,
  phase: (n: number, name: string) => `Phase ${n}: ${name}`,
  phaseDone: (done: number, total: number) => `${done} of ${total} done`,
  complete: 'complete',
  noDangers: 'No one is blocked today, and everyone flagged for care can already use MFA.',
  where: 'Where:',
  filterCount: (label: string, n: number) => `${label} (${n})`,
  safeChip: 'safe today',
  why: 'Why',
  authorIntent: "(the baseline author's intent, by",
  authorIntentEnd: ')',
  learn: 'Microsoft Learn →',
  cis: (c: string) => `CIS ${c}`,
  careTitle: (names: string) => `Handle with care. ${names}`,
  operatorUnsafe: 'Register a passkey or FIDO2 key and complete one MFA sign-in before enforcing this.',
  proposedName: 'Proposed name:',
  whoItTouches: 'Who it touches',
  kindLabel: 'Kind',
  goalLabel: 'Goal',
  evidenceLabel: 'Evidence',
  readiness: 'Readiness',
  last30: 'What the last 30 days say',
  affected: (names: string) => `affected: ${names}`,
  whatToDo: 'What to do',
  portalSteps: 'Portal steps',
  json: 'JSON',
  powershell: 'PowerShell',
  downloadJson: 'Download JSON',
  tellPeople: 'Tell your people',
  copyAnnouncement: 'Copy announcement',
  doneWhen: 'Done when',
  ifWrong: 'If it goes wrong',
  history: 'History',
  skipPlaceholder: 'Why does this not apply? (never "risk accepted")',
  confirmSkip: 'Confirm skip',
  skip: 'Skip this step…',
  markdown: {
    title: (tenant: string) => `# IAMAI rollout plan. ${tenant}`,
    range: (start: string, end: string, weeks: number) => `Start ${start} → target ${end} (${count(weeks, 'week')})`,
    dangers: '## Watch first',
    care: (names: string) => `Handle with care: ${names}`,
    blocked: (notes: string) => `Blocked: ${notes}`,
  },
}

export const LICENSING = {
  title: 'Licensing guide',
  empty: 'After a scan, this page shows what the licence enables, where seat counts fall short, and which goals are scored.',
  runScan: 'Run a scan',
  intro: 'IAMAI hardens what the tenant has. Every goal is scored against the best implementation the licence allows. Goals that need a missing tier are listed for reference, never as an accepted gap.',
  noP1: 'Without Entra ID P1 there is no Conditional Access; the plan is the free-tier ladder plus security defaults.',
  hasTitle: 'What the tenant has',
  columns: { capability: 'Capability', status: 'Status', seats: 'Seats', covers: 'Covers every user?' },
  enabled: 'enabled',
  notLicensed: 'not licensed',
  seats: (seats: number, consumed: number) => `${seats} (${consumed} assigned)`,
  covers: 'yes',
  short: (n: number) => `no. ${count(n, 'more user')} than seats`,
  goalsTitle: 'Goals by the licence they need',
  scored: 'scored',
  reference: 'reference only',
  ladderTitle: 'The free-tier ladder',
  /** C20: a rung with no step says why, rather than being dead text. */
  ladderNoStep: 'Rungs without a link are done outside Conditional Access, in the settings each one names.',
  openStep: 'Open the step →',
  ladderIntro: 'The spine of every plan, regardless of licence: curated from Microsoft guidance.',
  ladderInPlan: "Every item below is a step in this tenant's plan, with this tenant's own numbers against it.",
  nextAfterScan: 'Next: Findings',
  caps: {
    entraP1: 'Entra ID P1',
    entraP2: 'Entra ID P2',
    intune: 'Intune',
    workloadIdPremium: 'Workload Identities Premium',
    globalSecureAccess: 'Global Secure Access',
    defenderForCloudApps: 'Defender for Cloud Apps',
    purviewInsiderRisk: 'Purview Insider Risk',
  } as Record<string, string>,
}

export const READS = {
  title: 'What IAMAI reads',
  intro:
    'Everything IAMAI requests from Microsoft Graph, generated from the same list the code runs from.',
  lanes: {
    '0': 'On every load: configuration',
    A: 'On every scan: inventory',
    B: 'On every scan: sign-in records',
    'on-demand': 'Only after a baseline is picked',
  } as Record<string, string>,
  columns: { data: 'Data', endpoint: 'Endpoint', api: 'API', permissions: 'Permissions', gate: 'When it can fail', why: 'Why' },
  next: 'Next: Connect',
}
