// Page copy. Voice: IAMAI is the subject, or the sentence is imperative. No
// first person, no reassurance adjectives, no developer vocabulary.
import { count } from './statements.ts'

export const SHELL = {
  wordmark: 'IAMAI',
  tagline: 'Conditional Access rollout planner',
  tenantTooltip: (tenantId: string, username: string) => `Tenant ID ${tenantId} · signed in as ${username}`,
  lightTheme: 'Light theme',
  darkTheme: 'Dark theme',
  themeTooltip: 'Switch between dark and light themes',
  forget: 'Forget this tenant',
  // Error boundary (prompt 20 §2)
  errorTitle: 'This page hit an error',
  errorCalloutTitle: 'Nothing in the tenant changed',
  errorBody:
    'The page could not finish drawing. The saved scan, Setup answers and plan on this device are intact. Download the diagnostics to report the problem, or start over from the Start step.',
  errorDiagnostics: 'Download diagnostics (redacted)',
  errorStartOver: 'Start over',
  errorDetail: (message: string) => `Technical detail: ${message}`,
  // Scan age (prompt 20 §9)
  basedOn: (when: string) => `Based on the scan from ${when}.`,
  rescan: 'Re-scan',
  scanStale: (days: number) => `This scan is ${days} days old. Numbers, names and sign-in evidence may have moved on.`,
  scanStaleAction: 'Re-scan the tenant',
  forgetTooltip: 'Deletes everything IAMAI stored for this tenant on this device, then signs out',
  printHeader: (tenant: string, date: string, by: string) => `IAMAI plan for ${tenant} · prepared ${date} by ${by}`,
  footerLeft: 'Read-only · nothing leaves your browser',
  footerFollow: 'Made by',
  footerAuthor: 'Lachlan Robinette',
  footerGithub: 'GitHub',
  footerSource: 'Source',
  needs: 'Needs:',
  next: (label: string) => `Next: ${label}`,
  steps: {
    start: 'Start',
    connect: 'Connect',
    baseline: 'Baseline',
    scan: 'Scan',
    mapping: 'Setup',
    coverage: 'Findings',
    roadmap: 'Roadmap',
    licensing: 'Licensing guide',
    reads: 'What IAMAI reads',
    inventory: 'Inventory',
  },
  loading: 'Loading…',
  signInError: 'Sign-in error:',
  scanNeedsConnect: 'The scan reads the tenant into a local record. Connect a tenant first.',
  connectLink: 'Connect a tenant',
  inventoryNeedsConnect: 'The inventory comes from a scan of a connected tenant. Connect a tenant first.',
}

export const START = {
  headline: 'Turn your Conditional Access baseline into a dated rollout plan that names who each step touches before anything is enforced.',
  subhead:
    "IAMAI reads your tenant's policies, people, and sign-in records, compares them with a proven baseline, and produces a dated plan: who each step touches, what could go wrong, and the exact change to make.",
  caveat: 'Predicted impact, confirmed in report-only.',
  cta: 'Get started',
  howTitle: 'How it works',
  how: [
    { icon: 'shield', title: 'Connect', text: 'A read-only sign-in. IAMAI cannot change anything in the tenant.' },
    { icon: 'policy', title: 'Choose a baseline', text: 'Start from a maintained policy set, or upload a package.' },
    { icon: 'chart', title: 'Scan and see readiness', text: 'Who could pass MFA today, who needs a hand, and who is blocked right now: by name.' },
    { icon: 'check', title: 'Follow the roadmap', text: 'Dated phases, the changes that are safe today, and the danger areas named.' },
  ] as const,
  needTitle: "What you'll need",
  need: [
    'A Global Administrator or Global Reader account.',
    'Entra ID P1 for sign-in records. IAMAI works without it, with less evidence.',
    'About ten minutes for the first scan.',
  ],
  readsTitle: 'What IAMAI reads, and why',
  reads: [
    'The Conditional Access configuration: to compare it with the baseline.',
    'User, device, and licence inventory: to size every step\'s impact.',
    'Recent interactive sign-in records: to check that MFA works before anything is enforced.',
  ],
  readsLink: 'The full list, with every endpoint and permission →',
  neverTitle: 'What IAMAI never does',
  never: [
    'No changes to the tenant: the app holds read-only permissions only.',
    'Nothing leaves the browser. There is no server.',
    'No account required with anyone.',
  ],
  sourceBefore: 'IAMAI runs entirely in the browser and only reads. ',
  sourceLink: 'The source is public',
  sourceAfter: ', so anyone can verify that.',
}

export const CONNECT = {
  title: 'Connect',
  does: "Signs in read-only so IAMAI can read the tenant's configuration and inventory.",
  needs: 'a Global Administrator or Global Reader account',
  next: 'Baseline',
  signedInTo: 'Signed in to',
  as: 'as',
  tenantId: 'Tenant ID',
  savedScan: (when: string, users: number | null) =>
    `A scan from ${when}${users ? ` (${count(users, 'user')})` : ''} is saved on this device: go straight to`,
  findings: 'Findings',
  or: 'or',
  roadmap: 'Roadmap',
  signOut: 'Sign out',
  bullets: [
    'IAMAI is read-only. It never creates, edits, or deletes anything in the tenant: not even report-only policies.',
    'Admin consent creates an enterprise app named IAMAI in the tenant. To remove all access later, delete that enterprise app: nothing else is left behind.',
  ],
  sourceBefore: 'IAMAI runs entirely in the browser and only reads. ',
  sourceLink: 'The source is public',
  sourceAfter: ', so anyone can verify that.',
  signIn: 'Sign in with Microsoft',
}

/** Branches: none, all required, none required, some required (prompt 19 §A2). */
function BASELINE_QUESTIONS({ total, required }: { total: number; required: number }): string {
  if (total === 0) return 'Setup has nothing to ask'
  if (required === total) return `Setup will ask ${count(total, 'question')} (all required)`
  if (required === 0) return `Setup will ask ${count(total, 'question')} (none required)`
  return `Setup will ask ${count(total, 'question')} (${required} required)`
}

export const BASELINE = {
  title: 'Baseline',
  does: 'Picks the target policy set the rollout plan aims for.',
  next: 'Scan',
  fetching: (n: number) => `Fetching ${count(n, 'file')} from GitHub at the pinned commit…`,
  reading: (n: number) => `Reading ${count(n, 'uploaded file')}…`,
  uploadedSource: (n: number) => `uploaded package (${count(n, 'file')})`,
  load: 'Load this baseline',
  orUpload: 'or upload a package',
  howToPackage: 'how to make one',
  loadFailed: 'Load failed.',
  aboutTitle: 'About this baseline',
  by: 'by',
  repository: 'repository',
  capturedOn: (date: string) => `Captured ${date}`,
  commit: (c: string) => `version ${c.slice(0, 7)}`,
  noDescription: 'No description provided.',
  filesIn: (n: number) => `${count(n, 'file')} in this baseline`,
  targets: (tiers: string) => `targets ${tiers}`,
  loadedTitle: (source: string) => `Loaded: ${source}`,
  uploadLabel: 'Upload baseline policy files',
  summaryLine: (policies: number, goals: number, questions: { total: number; required: number }) =>
    `${count(policies, 'policy', 'policies')} · ${count(goals, 'security goal')} · ${BASELINE_QUESTIONS(questions)}`,
  authorNote: 'For the baseline author: these lines describe the export, not this tenant.',
  policiesReady: (n: number) => `${count(n, 'policy', 'policies')} ready to compare.`,
  unusable: (n: number) =>
    `${count(n, 'policy', 'policies')} in the source cannot be used yet (exported without targets): this does not affect the plan.`,
  choices: (n: number) => `${count(n, 'choice')} to make in Setup (${n === 1 ? 'two styles of the same policy' : 'alternative styles of the same policies'}).`,
  references: (n: number) => `${count(n, 'reference')} to the tenant. Setup resolves the ones that need a human; the rest are automatic.`,
  technical: 'Technical details',
  considered: (considered: number, parsed: number) => `${count(considered, 'file')} considered, ${parsed} parsed cleanly.`,
  duplicates: (n: number) => `${count(n, 'duplicate pair')} collapsed.`,
  parseErrors: (n: number, paths: string) => `${count(n, 'file')} failed to parse and ${n === 1 ? 'was' : 'were'} skipped: ${paths}`,
  unusableList: (names: string) => `Exported without their targets (the people they apply to were lost in the export), so they cannot be compared: ${names}`,
  fetchFailures: (n: number) => `${count(n, 'file')} could not be fetched from the source repository.`,
  labState: 'Baseline policy states are the author\'s lab state; every baseline policy is treated as intended-enforced unless a manifest says otherwise.',
}

export const SCAN = {
  title: 'Scan',
  does: "Reads the tenant's configuration, inventory, and sign-in records into a local record on this device. Nothing is written; nothing leaves the browser.",
  needs: 'connected tenant',
  next: 'Setup',
  scan: 'Scan tenant',
  rescan: 'Re-scan tenant',
  diagnostics: 'Download diagnostics (redacted)',
  failed: 'Scan failed.',
  sessionExpired: 'Your Microsoft session expired. Sign in again to continue.',
  sessionExpiredBody: 'The scan is paused where it got to; nothing collected so far is lost.',
  signInAgain: 'Sign in again',
  usingSaved: (when: string) => `Scan completed ${when} · saved on this device. Re-scan any time for fresh numbers.`,
  slow: "Microsoft's sign-in record service is slow right now: this can take several minutes on larger tenants. Everything else is already collected.",
  details: 'Details',
  reading: 'reading…',
  found: (label: string, n: number) => `${label}. ${n} found`,
  sectionsBar: (done: number, total: number) => `Configuration and inventory · ${done} of ${total}`,
  signInsBar: (rows: number, oldest: string | null) => `Sign-in records · ${rows} read${oldest ? ` · covered back to ${oldest}` : ''}`,
  waitingFirstBatch: 'Sign-in records · waiting for the first batch from Microsoft (about a minute)',
  nowReading: (labels: string[]) => (labels.length > 0 ? `Now reading: ${labels.join(', ')}…` : 'Finishing up…'),
  elapsed: (t: string) => `${t} elapsed`,
  completeTitle: 'Scan complete',
  completeLine: (users: number, policies: number, window: string | null) =>
    `${count(users, 'user')} · ${count(policies, 'policy', 'policies')} · ${window ? `sign-in records for ${window}` : 'no sign-in records'}`,
  tabs: { readiness: 'Readiness', inventory: 'Inventory' },
  readiness: 'Readiness',
  signInRecords: 'Sign-in records:',
  complete: 'complete',
  evidenceStatus: {
    ok: 'complete',
    partial: 'partly collected',
    insufficient: 'too few to use',
    disabled: 'not available on this licence',
    error: 'could not be read',
    pending: 'not collected yet',
    started: 'reading…',
  } as Record<string, string>,
  covering: (from: string, to: string) => `covering ${from} to ${to}`,
  pending: 'Sign-in records have not been collected yet; states below are based on registered methods only',
  unusable: 'States below are based on registered methods only; nothing can be Verified without usable records',
  mfaState: 'MFA state',
  activity: 'Activity',
  rollout: 'Rollout',
  blockedToday: (n: number) => `Blocked today: ${count(n, 'user')} whose most recent sign-in failed Conditional Access.`,
  noPolicyIdentified: 'No policy identified',
  users: (n: number) => `${count(n, 'user')}`,
  search: 'Search name or sign-in address…',
  searchLabel: 'Search users',
  clearFilters: 'Clear filters',
  noMatch: 'No users match these filters.',
  legend: 'Legend',
  /** "12 · 40%": count first, share of enabled users second (ux-review-04 §1). */
  rolloutValue: (n: number, enabled: number) => (enabled === 0 ? '0' : `${n.toLocaleString('en')} · ${Math.round((n / enabled) * 100)}%`),
  columns: {
    user: 'User',
    signInAddress: 'Sign-in address',
    admin: 'Admin',
    activity: 'Activity',
    mfa: 'MFA state',
    method: 'Strongest method',
    reasons: 'Reasons',
    care: 'Handle with care',
  },
  yes: 'yes',
  guest: 'Guest',
  care: 'care',
  createdAgo: (rel: string) => `created ${rel}`,
  mfaVia: (method: string, rel: string) => `MFA via ${method} ${rel}`,
  mfaCompleted: (rel: string) => `MFA completed ${rel}`,
  authenticatorStale: 'Authenticator app out of date',
  authenticatorCurrent: 'Authenticator app up to date',
  sections: {
    'config:caPolicies': 'Conditional Access policies',
    'config:namedLocations': 'Named locations',
    'config:authStrengths': 'Authentication strengths',
    'config:authMethodsPolicy': 'Authentication methods policy',
    'config:securityDefaults': 'Security defaults',
    'config:crossTenantAccess': 'Cross-tenant access',
    'config:roleAssignments': 'Role assignments',
    'config:pimEligibility': 'PIM eligibility',
    'config:subscribedSkus': 'Licences',
    'config:organization': 'Organisation',
    'config:me': 'The signed-in account',
    'config:meMemberOf': 'Its groups',
    registrationDetails: 'MFA registration',
    users: 'People',
    devices: 'Devices',
    spActivity: 'Service principal activity',
    authMethods: 'Registered methods',
    appSignInSummary: 'App usage',
    signInEvidence: 'Sign-in records',
  } as Record<string, string>,
}

export const FINDINGS = {
  title: 'Findings',
  does: "What the scan found in the tenant: what's working, what needs attention, and why.",
  next: 'Roadmap',
  needsScan: 'scan complete',
  needScan: 'Run a scan in the Scan step',
  needsBaseline: 'baseline loaded',
  needBaseline: 'Load a baseline in the Baseline step',
  blocked: 'Findings need a scan.',
  runScan: 'Run a scan',
  and: 'and',
  loadBaseline: 'load a baseline',
  resolving: 'Reading group memberships…',
  basedOn: (when: string) => `Based on the scan from ${when}.`,
  rescan: 'Re-scan',
  tabs: { summary: 'Summary', working: "Here's what's working", attention: "Here's what needs attention", details: 'Details' },
  sinceCheckpoint: (when: string) => `Since the last checkpoint (${when}):`,
  assumed: (groups: number, users: number) =>
    `IAMAI inferred ${count(groups, 'exclusion group')} and ${count(users, 'likely break-glass account')} from how the policies use them. Confirm them in`,
  assumedLink: 'Setup',
  assumedAfter: 'to remove the hedging.',
  tiles: { inPlace: 'In place', partly: 'Partly', missing: 'Missing', scored: 'of scored goals in place', proven: 'of enabled users proved MFA in the last 30 days', toSetUp: 'enabled users to set up before enforcement' },
  nothingInPlace: 'Nothing is fully in place yet: that is what the plan is for.',
  allInPlace: 'Everything the baseline asks for is in place. Re-scan periodically; drift is flagged.',
  policiesInvolved: 'Policies involved',
  reportOnly: 'report-only',
  delivers: 'delivers it',
  tooWeak: 'applies but too weak',
  disabledCandidate: 'switched off',
  whyNot: 'Why not fully',
  expected: '(expected)',
  usersCount: (n: number) => `${count(n, 'user')}`,
  seeStep: 'See the step for this in the Roadmap →',
  // Control bar and badges (prompt 17 §2)
  groupBy: 'Group by',
  sortBy: 'Sort by',
  groupNone: 'None',
  groupDomain: 'Domain',
  sort: { priority: 'Priority', value: 'Security value', effort: 'Effort', disruption: 'Disruption' } as Record<string, string>,
  whyMatters: 'Why this matters',
  howToFix: 'How to fix this',
  fixText: (goal: string) => `The Roadmap has a dated step for "${goal}" with the exact change, who it touches, and what to check before enforcing.`,
  fixLink: 'Open the step',
  badge: { value: 'Value', effort: 'Effort', disruption: 'Disruption' },
  learn: 'Microsoft Learn →',
  cis: (c: string) => `CIS ${c}`,
  notInScope: 'Not in scope for this tenant',
  couldNotEvaluate: 'Could not be evaluated',
  notInBaseline: 'Policies not in the baseline',
  everyPolicyMaps: 'Every policy maps to a goal.',
  fineToKeep: 'fine to keep; not part of this baseline',
  housekeeping: 'Housekeeping',
  naming: (share: number, pattern: string, outliers: string) =>
    `Naming: ${share}% of the policies share the prefix "${pattern}"${outliers ? `; outliers: ${outliers}` : ''}`,
  noNaming: "Naming: no dominant naming convention yet: the plan uses the baseline's",
  consolidate: (goal: string, n: number) => `${goal} is delivered by ${count(n, 'policy', 'policies')}: consider consolidating`,
  microsoftManaged: (list: string) => `Microsoft-managed policies: ${list}`,
  delta: {
    goals: (from: number, to: number) => `goals in place ${from} → ${to}`,
    verified: (n: number, more: boolean) => `${n} ${more ? 'more' : 'fewer'} verified ${n === 1 ? 'user' : 'users'}`,
    noMethod: (n: number, fewer: boolean) => `${n} ${fewer ? 'fewer' : 'more'} without a method`,
    regressed: (n: number) => `${count(n, 'goal')} regressed: check for policy changes outside the plan`,
    nothing: 'nothing has changed.',
  },
}

export const ROADMAP = {
  title: 'Roadmap',
  does: 'The dated plan from here to the baseline, with the danger areas named.',
  needsScan: 'scan complete',
  needScan: 'Run a scan in the Scan step',
  needsBaseline: 'baseline loaded',
  needBaseline: 'Load a baseline in the Baseline step',
  preparing: 'Preparing the plan (reading group memberships)…',
  blocked: 'The plan builds from a scan and a baseline.',
  runScan: 'Run a scan',
  and: 'and',
  loadBaseline: 'load a baseline',
  basedOn: (when: string) => `Based on the scan from ${when}.`,
  rescan: 'Re-scan',
  tabs: { overview: 'Overview', timeline: 'Timeline', danger: 'Danger areas', steps: 'Steps' },
  weeksBadge: (w: number) => `${w}w`,
  paceLabel: 'Pace:',
  // Size bands (§A3): the pace follows the tenant; the band can be overridden.
  bands: {
    small: { label: 'Small', text: 'Up to 30 active users: about 4 weeks, with a 2-week registration and verification window.' },
    mid: { label: 'Mid', text: '31 to 300 active users: about 8 weeks, with a 4-week registration and verification window.' },
    large: { label: 'Large', text: 'More than 300 active users: about 12 weeks, with a 6-week registration and verification window.' },
  } as Record<string, { label: string; text: string }>,
  bandWord: { small: 'small-tenant', mid: 'mid-size', large: 'large-tenant' } as Record<string, string>,
  bandAuto: (active: number, label: string) => `${count(active, 'active user')}: ${label} band, detected`,
  bandOverride: (active: number, label: string) => `${count(active, 'active user')}: ${label} band, your choice`,
  bandReset: 'Back to detected',
  expected: (weeks: number) => `this pace usually takes ${count(weeks, 'week')}`,
  verificationWindow: (days: number) => `Registration and verification window · ${days} days`,
  verificationText: 'Everyone active registers Microsoft Authenticator and completes one MFA sign-in; re-scans track it.',
  verificationDone: 'Verification complete: the window is skipped and the waves pull forward.',
  showCompleted: 'Show completed',
  hideCompleted: 'Hide completed',
  completedHidden: (n: number) => `${count(n, 'completed step')} hidden`,
  day0: 'Day 0',
  day0Text: (n: number) => `${n === 1 ? '1 policy is' : `${n} policies are`} created in report-only in one batch: nobody is affected.`,
  observation: (days: number) => `Observation window · ${days} days`,
  observationText: 'Every new policy collects report-only evidence at the same time.',
  wave: (n: number, name: string) => `Wave ${n} · ${name}`,
  blockedBy: 'Blocked by',
  setupQuestionLink: (n: number) => `Setup question ${n}`,
  sortBy: 'Sort by',
  sortSchedule: 'Schedule',
  currentScope: 'Today the policy targets',
  safeToday: (n: number) => `Safe today (${n}):`,
  safeTodayWhy: (tenant: string) => `Nobody in ${tenant} used what these block in the last 30 days, so enforcing them is predicted to interrupt no one.`,
  dangers: (high: number) => `${count(high, 'thing needs', 'things need')} care before the plan starts:`,
  dangersAfter: 'the Danger areas tab names the people and the exact settings.',
  dangersMedium: (n: number) => `${count(n, 'area')} to watch, none urgent: the Danger areas tab names the people.`,
  lastStep: 'This is the last step. Re-scan after each change to update progress.',
  rescanProgress: 'Re-scan to update progress',
  blockedSteps: (n: number) =>
    `${count(n, 'step is', 'steps are')} blocked right now; each one says exactly what unblocks it. Most clear once the verification campaign in phase 2 lands.`,
  startDate: 'Plan start date:',
  save: 'Save plan',
  copyMarkdown: 'Copy as Markdown',
  copied: 'Copied ✓',
  load: 'Load plan',
  print: 'Print the plan',
  couldNotRead: 'could not read the plan file',
  phase: (n: number, name: string) => `Phase ${n}: ${name}`,
  phaseDone: (done: number, total: number) => `${done} of ${total} done`,
  complete: 'complete',
  noDangers: 'Nothing alarming: no one is blocked today, and everyone flagged for care can already use MFA.',
  where: 'Where:',
  filterCount: (label: string, n: number) => `${label} (${n})`,
  safeChip: 'safe today',
  why: 'Why',
  authorIntent: "(the baseline author's intent, by",
  authorIntentEnd: ')',
  learn: 'Microsoft Learn →',
  cis: (c: string) => `CIS ${c}`,
  careTitle: (names: string) => `Handle with care. ${names}`,
  operatorUnsafe: 'Register a passkey or FIDO2 key and complete one MFA sign-in before enforcing this.',
  proposedName: 'Proposed name:',
  whoItTouches: 'Who it touches',
  readiness: 'Readiness',
  last30: 'What the last 30 days say',
  affected: (names: string) => `affected: ${names}`,
  whatToDo: 'What to do',
  portalSteps: 'Portal steps',
  json: 'JSON',
  powershell: 'PowerShell',
  downloadJson: 'Download JSON',
  tellPeople: 'Tell your people',
  copyAnnouncement: 'Copy announcement',
  doneWhen: 'Done when',
  ifWrong: 'If it goes wrong',
  history: 'History',
  skipPlaceholder: 'Why does this not apply? (never "risk accepted")',
  confirmSkip: 'Confirm skip',
  skip: 'Skip this step…',
  markdown: {
    title: (tenant: string) => `# IAMAI rollout plan. ${tenant}`,
    range: (start: string, end: string, weeks: number) => `Start ${start} → target ${end} (${count(weeks, 'week')})`,
    dangers: '## Danger areas',
    care: (names: string) => `Handle with care: ${names}`,
    blocked: (notes: string) => `Blocked: ${notes}`,
  },
}

export const LICENSING = {
  title: 'Licensing guide',
  empty: 'After a scan, this page shows what the licence enables, where seat counts fall short, and which goals are scored.',
  runScan: 'Run a scan',
  intro: 'IAMAI hardens what the tenant has. Every goal is scored against the best implementation the licence allows. Goals that need a missing tier are listed for reference, never as an accepted gap.',
  noP1: 'Without Entra ID P1 there is no Conditional Access; the plan is the free-tier ladder plus security defaults.',
  hasTitle: 'What the tenant has',
  columns: { capability: 'Capability', status: 'Status', seats: 'Seats', covers: 'Covers every user?' },
  enabled: 'enabled',
  notLicensed: 'not licensed',
  seats: (seats: number, consumed: number) => `${seats} (${consumed} assigned)`,
  covers: 'yes',
  short: (n: number) => `no. ${count(n, 'more user')} than seats`,
  goalsTitle: 'Goals by the licence they need',
  scored: 'scored',
  reference: 'reference only',
  ladderTitle: 'The free-tier ladder',
  ladderIntro: 'The spine of every plan, regardless of licence: curated from Microsoft guidance.',
  nextAfterScan: 'Next: Findings',
  caps: {
    entraP1: 'Entra ID P1',
    entraP2: 'Entra ID P2',
    intune: 'Intune',
    workloadIdPremium: 'Workload Identities Premium',
    globalSecureAccess: 'Global Secure Access',
    defenderForCloudApps: 'Defender for Cloud Apps',
    purviewInsiderRisk: 'Purview Insider Risk',
  } as Record<string, string>,
}

export const READS = {
  title: 'What IAMAI reads',
  intro:
    'Everything IAMAI requests from Microsoft Graph, generated from the same list the code runs from. All access is read-only; nothing in the tenant is created, changed, or deleted.',
  lanes: {
    '0': 'On every load: configuration',
    A: 'On every scan: inventory',
    B: 'On every scan: sign-in records',
    'on-demand': 'Only after a baseline is picked',
  } as Record<string, string>,
  columns: { data: 'Data', endpoint: 'Endpoint', api: 'API', permissions: 'Permissions', gate: 'When it can fail', why: 'Why' },
  next: 'Next: Connect',
}
