// The Plan surface (prompt 48 Parts 2-4, target-state §5-§6). The header line,
// the assumptions strip, the wave and row wording, the step sections, the
// footer. Product voice: IAMAI is the subject or the sentence is imperative.
import { count } from './statements.ts'

export const PLAN = {
  title: 'Plan',
  /** The one header line: steps, in place, finish, weeks, and what waits. */
  header: (total: number, inPlace: number, finish: string, weeks: number, waiting: string) =>
    `${count(total, 'step')} · ${inPlace} in place · ${finish} · ${count(weeks, 'week')}${waiting ? ` · ${waiting}` : ''}`,
  cannotFinish: (waiting: string) => `${waiting}; nothing is dated until it clears`,
  constraintTip: 'What set the plan length',
  next: 'next',
  settings: 'Plan settings',
  settingsTitle: 'Plan settings',
  startDate: 'Start date',
  resetStart: 'Clear the date to reset to the default, the next working day.',
  freezeFrom: 'Change freeze from',
  freezeTo: 'until',
  freezeClear: 'Clear freeze',
  close: 'Close',
  // Assumptions strip.
  assumes: 'Assumes:',
  save: 'Save',
  confirm: 'confirm',
  change: 'change',
  answer: 'answer',
  noneFound: 'none found, choose one',
  signals: (n: number, list_: string) => `${count(n, 'signal')}: ${list_}`,
  assumption: {
    emergencyAccess: (n: number) => (n === 0 ? 'emergency access none found, choose one' : `emergency access ${count(n, 'account')}`),
    exclusionsGroup: (name: string | null) => (name ? `exclusions group ${name}` : 'exclusions group none yet'),
    countries: (codes: string[]) => (codes.length === 0 ? 'sign-in countries none' : `sign-in countries ${codes.join(', ')}`),
    trustedLocations: (n: number) => (n === 0 ? 'trusted locations none' : `trusted locations ${n}`),
    serviceAccounts: (n: number) => (n === 0 ? 'service accounts none' : `service accounts ${count(n, 'account')}`),
    sharedDevices: (n: number) => (n === 0 ? 'shared devices none' : `shared devices ${n}`),
    timeZone: (zone: string) => `time zone ${zone.split('/').pop()?.replace(/_/g, ' ') ?? zone}`,
    // The three questions the tool cannot answer from evidence. Once answered the
    // chip reflects the answer and offers `change`, not `answer` (prompt 49.1 item 9).
    mailDevices: 'mail-sending devices none seen',
    mailDevicesListed: (n: number) => `mail-sending devices ${count(n, 'listed', 'listed')}`,
    travel: 'people who travel or work abroad none seen',
    travelListed: (n: number) => `people who travel or work abroad ${count(n, 'listed', 'listed')}`,
    partner: 'partner or MSP access none seen',
    partnerListed: (n: number) => `partner or MSP access ${count(n, 'listed', 'listed')}`,
  },
  /** The editor's first line: what the chip's short label leaves out (prompt 48.1 item 12). */
  explain: {
    mailDevices: 'None seen in the last 30 days. Answering adds an SMTP-relay step for printers or apps that send mail.',
    travel: 'None seen in the records. Answering adds notice and a travel exclusion.',
    partner: 'No service-provider sign-ins seen. Answering adds a partner exclusion.',
  } as Record<string, string>,
  editor: {
    emergencyAccount: 'Search people',
    group: 'Search groups',
    location: 'Search named locations',
    country: 'Add a country',
    person: 'Search people',
    timeZone: 'Time zone',
    freeText: 'One per line',
    mailDevicesPrompt: 'List any printers or apps that send mail (one per line), or leave empty.',
    travelPrompt: 'List the people or teams who travel or work abroad, or leave empty.',
    partnerPrompt: 'Name the partner or MSP tenants, or leave empty.',
    signalsFor: {
      name: 'named like an emergency account',
      onmicrosoft: 'signs in with the onmicrosoft.com address',
      globalAdmin: 'Global Administrator',
      excludedEverywhere: 'excluded from every policy',
      noLicence: 'no licence',
    } as Record<string, string>,
    serviceSignals: {
      name: 'named like a service account',
      noMethod: 'no MFA method',
      neverInteractive: 'never signs in interactively',
      legacyOnly: 'legacy authentication only',
      exchangeOnly: 'Exchange plans only',
      noProfile: 'no name or job title',
    } as Record<string, string>,
  },
  // Wave headers and rows.
  day0: 'Before anything else',
  wave: (n: number, dates: string, areas: string, after?: string) => `Wave ${n} · ${dates} · ${areas}${after ? ` · after ${after}` : ''}`,
  /** The row's short blocked reason (item 14): "after: emergency access". */
  afterShort: (reason: string) => `after: ${reason}`,
  day0Dates: (dates: string) => `Before anything else · ${dates}`,
  familyName: { mfa: 'MFA', admin: 'Admin hardening', device: 'Devices', guest: 'Guests', block: 'Low-impact blocks', location: 'Locations', risk: 'Risk', other: 'Sessions' } as Record<string, string>,
  and: (a: string, b: string) => `${a} and ${b}`,
  enforcedPending: 'Enforced · verified on the next scan',
  who: {
    nobody: 'nobody affected',
    admins: (n: number) => count(n, 'admin'),
    people: (n: number) => count(n, 'person', 'people'),
    named: (names: string[]) => names.join(', '),
    now: 'now',
  },
  footer: {
    inPlace: (n: number) => `Already in place (${n})`,
    doesNotApply: (n: number) => `Doesn't apply here (${n})`,
    housekeeping: (n: number) => `Housekeeping (${n})`,
    goalReason: (goal: string, reason: string) => `${goal}: ${reason}`,
    json: 'JSON',
    notInBaseline: (name: string, state: string) => `${name} (${state}): not in the baseline, fine to keep.`,
    rename: (name: string, to: string) => `${name} is off the naming convention; rename to ${to}.`,
    notAssessed: (name: string) => `${name}: also in the baseline, not assessed.`,
    checksNotRun: (line: string) => line,
  },
  // The step body (target-state §6).
  step: {
    why: 'Why',
    whoTouches: 'Who this touches',
    doIt: 'Do it',
    dates: 'Dates',
    doneWhen: 'Done when',
    ifWrong: 'If it goes wrong',
    tellPeople: 'Tell your people',
    learn: 'Learn →',
    cis: (c: string) => `CIS ${c}`,
    portalSteps: 'Portal steps',
    json: 'JSON',
    powershell: 'PowerShell',
    downloadJson: 'Download JSON',
    omitsJson: (labels: string[]) => {
      const list = labels.join(', ')
      const one = labels.length === 1
      const head = list.charAt(0).toUpperCase() + list.slice(1)
      return `${head} ${one ? "doesn't" : "don't"} exist yet. This JSON omits ${one ? 'it' : 'them'}; re-download after that step.`
    },
    copy: 'Copy',
    andMore: (n: number) => `and ${count(n, 'more')}`,
    exportCsv: 'Export CSV',
    recovery: 'Recovery card →',
    close: 'Close',
    datesLine: (announce: string, reportOnly: string, enforce: string) => `Announce ${announce} · Report-only from ${reportOnly} · Enforce ${enforce}`,
    ring: (name: string, date: string, people: number) => `${name} ${date} (${count(people, 'person', 'people')})`,
    operatorInScope: (signIns: number) => `Your account is in scope: ${count(signIns, 'sign-in')} in 30 days.`,
    // More.
    more: 'More',
    couldGoWrong: 'What could go wrong',
    prerequisites: 'Prerequisites',
    waitsOnThis: 'What waits on this',
    exitCriteria: 'Exit criteria',
    forHelpDesk: 'For the help desk',
    forManager: 'For your manager',
    copyAsPrompt: 'Copy as prompt',
    cantSee: "What IAMAI can't see",
    skip: 'Skip this step',
    appliesHere: 'applies here',
    nothingWaits: 'Nothing waits on this step.',
    noPrerequisites: 'Nothing has to exist first.',
  },
  needsScan: 'Nothing to plan until the first scan.',
  scanLink: 'Scan the tenant',
} as const
