// Population copy (roadmap-v2.md §3): every number carries its basis; names
// stay bounded; the export is generated in the browser.
import { count } from './statements.ts'

export const POPULATION = {
  basis: (n: number, enabled: number, percent: number) => `${n.toLocaleString('en-AU')} of ${enabled.toLocaleString('en-AU')} enabled users (${percent}%)`,
  ofWhomNoMethod: (n: number) => `, of whom ${n.toLocaleString('en-AU')} ${n === 1 ? 'has' : 'have'} no MFA method`,
  ofWhomNoDevice: (n: number) => `, of whom ${n.toLocaleString('en-AU')} ${n === 1 ? 'owns' : 'own'} no compliant device`,
  ofWhomSeen: (n: number) => `, of whom ${n.toLocaleString('en-AU')} ${n === 1 ? 'was' : 'were'} seen using what this blocks`,
  nobody: 'Nobody is in scope of this step.',
  everyoneNamed: (n: number) => `All ${count(n, 'person', 'people')}:`,
  riskiestTitle: (n: number) => `The ${n} riskiest by name:`,
  riskiestNote: 'Riskiest first: no MFA method, then admins, then never signed in, then unverified.',
  cohortsTitle: 'By cohort',
  cohortsPercentOnly: 'Counts are shown as shares of the population at this size.',
  exportCsv: 'Export the list (CSV)',
  exportNote: 'The export is generated in the browser from the scan; nothing leaves this machine.',
  andMore: (n: number) => `and ${count(n, 'more')}`,
  cohort: {
    department: 'Department',
    licence: 'Licence',
    activity: 'Activity',
    mfa: 'MFA state',
    device: 'Device state',
  },
  labels: {
    noDepartment: 'No department',
    p2: 'Entra ID P2',
    p1: 'Entra ID P1',
    unlicensed: 'No Entra ID P1/P2',
    active: 'Active (30 days)',
    dormant: 'Dormant',
    neverSignedIn: 'Never signed in',
    verified: 'Verified',
    likelyViable: 'Likely viable',
    notChallenged: 'Not challenged yet',
    unverified: 'Unverified',
    none: 'No method',
    compliant: 'Compliant or hybrid-joined device',
    noDevice: 'No compliant device',
    devicesUnknown: 'Device data not readable',
  },
  reasons: {
    noMethod: 'no MFA method',
    admin: 'admin',
    neverSignedIn: 'never signed in',
    unverified: 'unverified',
    highCare: 'handle with care',
    noDevice: 'no compliant device',
    seen: 'seen using what this blocks',
  },
  csv: {
    name: 'Name',
    upn: 'User principal name',
    department: 'Department',
    activity: 'Activity',
    mfa: 'MFA state',
    device: 'Device state',
    admin: 'Admin',
    risk: 'Why it matters',
    yes: 'yes',
    no: 'no',
  },
}
