// Progress copy (roadmap-v2.md §5): detection notes, regressions, the journey,
// the calendar strip, slip reasons and the what-changed list.
import { count } from './statements.ts'

export const TRACK = {
  matchedByTag: 'matched by its plan tag',
  matchedByFingerprint: 'this policy already existed and covers this step',
  reportOnlyFound: (date: string) => `policy in report-only since ${date}`,
  enforced: (date: string) => `policy enforced on ${date}`,
  enforcedByOther: (name: string) => `${name} already enforces this`,
  modifiedAfter: (date: string) => `policy modified after enforcement on ${date}`,
  soak: (days: number, signIns: number, failures: number) => `${count(days, 'day')} in report-only, ${count(signIns, 'sign-in')}, ${count(failures, 'failure or interruption', 'failures or interruptions')}`,
  readyToEnforce: 'report-only evidence meets the exit criterion and every handle-with-care user is verified',
  evidence: { enough: 'enough sign-ins to judge', thin: 'too few sign-ins to judge yet', none: 'no sign-in evidence' },
  regression: {
    disabled: (name: string, since: string) => `${name} was disabled after ${since}; the goal is open again`,
    deleted: (name: string, since: string) => `${name} was deleted after ${since}; the goal is open again`,
    weakened: (name: string, since: string) => `${name} was weakened after ${since}; it no longer meets the baseline`,
    narrowed: (name: string, since: string) => `${name} covers fewer people than it did on ${since}`,
    goal: (since: string, what: string) => `changed since ${since}: the goal is ${what} again`,
  },
  stage: {
    planned: 'Planned',
    reportOnly: 'In report-only',
    soaking: 'Soaking',
    readyToEnforce: 'Ready to enforce',
    enforced: 'Enforced',
    verified: 'Verified',
    alreadyInPlace: 'Already in place',
  },
  slip: {
    prerequisite: (title: string) => `waiting for ${title}`,
    readiness: 'readiness below the threshold',
    noEvidence: 'no report-only evidence yet',
    operator: 'the signed-in account would be locked out',
    setup: 'a Setup question is unanswered',
    unknown: 'no recorded cause',
  },
}

export const PROGRESS = {
  blockersFirst: (n: number, held: number): string =>
    held === 0
      ? `${n === 1 ? 'One subject has' : `${n} subjects have`} must-fix checks outstanding; clear ${n === 1 ? 'it' : 'them'} before the rest of the plan runs.`
      : `${n === 1 ? 'One subject has' : `${n} subjects have`} must-fix checks outstanding, holding ${held === 1 ? '1 step' : `${held} steps`} that can deny access.`,
  tab: 'Progress',
  notStarted: 'Nothing has started yet: the plan below is the whole journey. Progress fills in from the next scan after the first policy is created.',
  headline: (started: string, enforced: number, total: number, soaking: number, slipped: number) =>
    `Started ${started}. ${enforced} of ${count(total, 'step')} enforced, ${soaking} soaking, ${slipped} slipped by more than a week.`,
  alreadyCovered: (n: number) => (n === 0 ? '' : `${count(n, 'step')} ${n === 1 ? 'was' : 'were'} already covered before the plan began.`),
  denominator: (total: number, trackable: number) => (total === trackable ? `${count(total, 'step')}` : `${count(total, 'step')}, of which ${trackable} are trackable`),
  projection: (projected: string, planned: string) => `At the current pace, finished by ${projected} (planned ${planned}).`,
  projectionOnTrack: (planned: string) => `On track for ${planned}.`,
  projectionNoPace: (planned: string) => `Planned finish ${planned}; the pace shows after the first enforcement.`,
  journeyTitle: 'The journey',
  journeyHint: 'Each tile is a step, coloured by its current ring; the band reads left to right from planned to verified.',
  stripTitle: 'Planned against actual, week by week',
  stripPlanned: (n: number) => `${n} planned`,
  stripActual: (n: number) => `${n} done`,
  stripWeek: (label: string) => `Week of ${label}`,
  stripLegend: 'Grey bars: steps planned to start that week. Green bars: steps that actually started. Hover a week for the counts.',
  absent: '—',
  perStepTitle: 'Every step, planned against actual',
  colPlanned: 'Planned',
  colActual: 'Actual',
  colSlip: 'Slip',
  colWhy: 'Why',
  slipDays: (d: number) => (d === 0 ? 'on time' : d > 0 ? `${count(d, 'day')} late` : `${count(-d, 'day')} early`),
  notStartedYet: 'not started',
  changesTitle: 'What changed since the last scan',
  changesNone: 'Nothing changed in the tenant since the last saved checkpoint.',
  changesNoCheckpoint: 'Save the plan once to record a checkpoint; changes since then show here on the next scan.',
  planned: 'planned',
  unplanned: 'unplanned',
  change: {
    created: (name: string) => `Policy created: ${name}`,
    modified: (name: string) => `Policy modified: ${name}`,
    enabled: (name: string) => `Policy enforced: ${name}`,
    reportOnly: (name: string) => `Policy moved to report-only: ${name}`,
    disabled: (name: string) => `Policy disabled: ${name}`,
    deleted: (name: string) => `Policy deleted: ${name}`,
    groupGrew: (name: string, from: number, to: number) => `Exclusion group ${name} grew from ${from} to ${count(to, 'member')}`,
    adminsAdded: (n: number) => `${count(n, 'admin')} added`,
    breakGlassUsed: (name: string, at: string) => `Break-glass account ${name} signed in on ${at}`,
  },
  driftNote: (n: number) => (n === 0 ? 'Every change was part of the plan.' : `${count(n, 'unplanned change')}: the drift to look at.`),
  revision: (n: number, at: string) => `Plan revision ${n}, ${at}`,
  revisionNote: {
    created: 'plan created',
    stepsAdded: (n: number) => `${count(n, 'new step')} appended after a re-scan`,
    stepsGone: (n: number) => `${count(n, 'step')} no longer applies`,
    baseline: (commit: string) => `baseline updated to ${commit}`,
    imported: 'imported from a version 1 plan file',
  },
}

export const SCHEDULE_TAB = {
  tab: 'Schedule',
  ownersTitle: 'Dates',
  colStep: 'Step',
  colStart: 'Starts',
  colEnd: 'Ends',
  colRing: 'Rings',
  exportIcs: 'Export to calendar (ICS)',
  icsNote: 'One calendar entry per scheduled step, from its first ring to its last, with the portal path, the done-when criteria and the rollback in the body.',
  unscheduled: 'not scheduled',
}

export const EXPORT_TAB = {
  tab: 'Export',
  planFile: 'Plan file',
  planFileText: 'Everything: steps, rings, evidence, history, Setup answers and checkpoints. Load it back on any machine.',
  pdf: 'The plan as a document',
  pdfText: 'The print layout: cover, waves, every step in full. Save as PDF from the print dialog.',
  changeRecord: 'Change record',
  changeRecordText: 'One row per step: what changed, when, who it touched, and how to undo it.',
  downloadChangeRecord: 'Download as Markdown',
  downloadChangeRecordCsv: 'Download as CSV',
  print: 'Print or save as PDF',
  markdown: 'Markdown',
  markdownText: 'The plan as text for a wiki or a ticket.',
}
