// Setup wizard copy: the questions a human answers, and the page around them.
import { count } from './statements.ts'

// Each question: a title, the question, an "Explain this" tip (help), and a
// one-line "Why this matters" (why). Nothing above a picker runs past two
// sentences.
export const SETUP_QUESTIONS = {
  breakGlass: {
    title: 'Emergency access',
    question: 'Which accounts are the emergency access (break-glass) admins?',
    help: 'Two cloud-only Global Administrator accounts, kept out of every policy and used only when everything else fails. IAMAI validates each pick and says exactly what to fix.',
    why: 'Every policy in the plan excludes these accounts, so a mistake can never lock the whole tenant out.',
  },
  globalExclusion: {
    title: 'Exclusion group',
    question: 'Which group holds the policy exclusions?',
    help: 'Usually a small assigned group containing only the break-glass accounts. If there is none, say so: creating it goes at the start of the plan.',
    why: 'One auditable group excluded from every policy keeps the escape hatch in a single place.',
  },
  countries: {
    title: 'Countries',
    question: 'Countries where your people sign in: add any that are missing.',
    help: 'Pre-selected from the countries seen in sign-in records and from each user\'s usage location. Sign-ins from anywhere else will be blocked once the geo policy is enforced.',
    why: 'The allowed list becomes a named location and the block-everywhere-else policy; a missing country is a lockout for whoever is there.',
  },
  highCare: {
    title: 'Handle with care',
    question: 'Who needs extra care?',
    help: 'Executives, VIPs, or anyone an accidental lockout would hurt. The changes still apply to them: enforcement waits until each is verified and every step that touches them names them.',
    why: 'These people are verified before anything is enforced and sequenced after the approach is proven.',
  },
  trustedLocations: {
    title: 'Trusted locations',
    question: 'Which named locations count as trusted?',
    help: 'Office IP ranges trusted for things like security-info registration. IAMAI checks each one for ranges that are too broad.',
    why: 'A trusted location lets registration and other sensitive actions happen only from the office network.',
  },
  serviceAccounts: {
    title: 'Service accounts',
    question: 'Are these service accounts?',
    help: 'Accounts that look like automation, mailboxes, or devices rather than people, each with the evidence that put it here. Confirm the real ones; reject the rest.',
    why: 'Service accounts cannot complete MFA: confirmed ones get carve-outs from the policies that would break them.',
  },
  timeZone: {
    title: 'Time zone',
    question: 'Which time zone should dates display in?',
    help: 'Affects display only; everything is stored in UTC.',
    why: 'Plan dates and sign-in times read correctly for whoever runs the rollout.',
  },
  frameworks: {
    title: 'Frameworks',
    question: 'Which security frameworks is the tenant working toward?',
    help: 'Findings and plan steps are tagged with the matching controls so the plan doubles as compliance evidence.',
    why: 'Tagged steps let the plan stand in as evidence for an audit.',
  },
  applicability: {
    title: 'Workloads',
    question: 'Are the detected workloads right?',
    help: 'Recommendations are switched off for workloads the tenant does not use. Correct any detection that is wrong.',
    why: 'A workload marked off removes its goals from the plan; one marked on adds them.',
  },
} as const

export const SETUP_PAGE = {
  title: 'Setup',
  does: 'A handful of questions about the tenant. Everything else is worked out from the scan.',
  needsBaseline: 'baseline loaded',
  needBaseline: 'Load a baseline in the Baseline step',
  needsScan: 'scan complete',
  needScan: 'Run a scan in the Scan step',
  next: 'Findings',
  blocked: 'Setup needs a loaded baseline and a scan.',
  loading: 'Loading the saved answers…',
  loadBaseline: 'Load a baseline',
  runScan: 'run a scan',
  progress: (answered: number, total: number, requiredLeft: number) =>
    `${answered} of ${total} answered · ${requiredLeft === 0 ? 'nothing required remaining' : `${requiredLeft} required remaining`}`,
  requiredList: (names: string[]) => `Still required: ${names.join(', ')}.`,
  questionNumber: (n: number) => `Question ${n}`,
  why: {
    inferredBreakGlass: 'directly excluded from an existing policy',
    inferredExclusion: 'the tenant\'s policies exclude this group the way a break-glass group is excluded',
    inferredServiceAccounts: 'excluded only from MFA or block policies, the way service accounts are',
    nameMatch: (m: string) => `name contains "${m}"`,
    cloudOnlyGa: 'cloud-only Global Administrator',
    trusted: 'marked trusted in the tenant',
  },
  doesNotExist: "Doesn't exist yet: add it to the plan",
  workloadEvidence: (name: string, reason: string) => `${name}. ${reason}`,
  workloadNames: {
    avd: 'Azure Virtual Desktop',
    copilot: 'Microsoft 365 Copilot',
    azureDevOps: 'Azure DevOps',
    intune: 'Intune',
    sharepoint: 'SharePoint',
    workload: 'Workload identities',
    agents: 'AI agents',
    azureManagement: 'Azure management',
  } as Record<string, string>,
  workloadReason: {
    seen: 'sign-ins seen in the last 30 days',
    notSeen: 'no sign-ins in the last 30 days',
    licence: (name: string) => `${name} licence present`,
    noLicence: (name: string) => `no ${name} licence`,
  },
  complete: 'that covers everything the plan needs. The optional ones below sharpen it.',
  incomplete: 'the required ones unlock the plan; the rest are optional.',
  autoResolved: (n: number) => `${n} baseline reference${n === 1 ? '' : 's'} resolved automatically.`,
  answered: 'Answered',
  required: 'Required',
  optional: 'Optional',
  searchUsers: 'Search users…',
  searchVips: 'Search users (executives, VIPs)…',
  searchGroups: 'Start typing a group name…',
  searchLocations: 'Search named locations…',
  usedInPolicy: 'used in a policy',
  members: (n: number) => `${n} member${n === 1 ? '' : 's'}`,
  toFix: (n: number) => `${n} to fix`,
  checksPassed: 'Checks passed',
  needsAttention: 'Needs attention before this is safe',
  nobodyNeedsCare: 'Nobody needs special care',
  careExplained: (n: number) =>
    `${n === 1 ? 'This user gets' : `These ${n} users get`} white-glove treatment: named on every step that touches them, verified before anything is enforced, and sequenced after the approach is proven.`,
  noNamedLocations: 'The tenant has no named locations yet.',
  markedTrusted: 'marked trusted in the tenant',
  notMarkedTrusted: 'not marked trusted',
  notApplicable: 'Not applicable',
  browserZone: (zone: string) => `${zone} (this browser)`,
  frameworkNone: 'Not sure / none',
  confirmedByOperator: 'confirmed in Setup',
  notUsed: 'marked as not used in Setup',
  yourAnswer: '(your answer)',
  detectionsRight: 'Detections look right',
  // ---- prompt 16 layout and feedback ----
  advanced: 'Advanced options',
  advancedHint: (n: number) => `${count(n, 'optional question')}: each one sharpens the plan.`,
  requiredOpen: (names: string[]) => `Still to answer: ${names.join(', ')}.`,
  allRequiredDone: 'Every required question is answered.',
  answeredAs: (choice: string) => `Answered: ${choice}`,
  edit: 'Edit',
  explain: 'Explain this',
  whyMatters: 'Why this matters',
  toast: (title: string) => `${title} saved`,
  nobody: 'nobody',
  noneChosen: 'none',
  notApplicableAnswer: 'not applicable',
  detected: 'Detected',
  markedInUse: 'Marked in use by you',
  markedOff: 'Marked off',
  offReasonPrompt: 'Why is this workload not in use? A short reason goes in the plan.',
  offReasonPlaceholder: 'e.g. no Azure subscriptions',
  confirmOff: 'Mark off',
  cancel: 'Cancel',
  // Service accounts (§A5)
  serviceEvidence: {
    name: (hit: string) => `name contains "${hit}"`,
    noMethod: 'no MFA method registered',
    neverInteractive: 'never signed in interactively',
    legacyOnly: 'uses legacy authentication',
    exchangeOnly: 'Exchange-only licence',
    noProfile: 'no department or job title',
  },
  confirmService: 'Confirm',
  notService: 'Not a service account',
  serviceConfirmed: (n: number) => `${count(n, 'service account')} confirmed`,
  serviceGroupFound: (name: string) => `All confirmed accounts are in ${name}: that group carries the carve-outs.`,
  serviceGroupMissing: 'No existing group holds all of them: the plan starts with a step to create the service accounts group.',
  serviceNoneLeft: 'No candidates left to review.',
  serviceCount: (n: number) => `${count(n, 'candidate')} found`,
  // Countries (§A4)
  countriesSeen: (n: number) => `${count(n, 'distinct user')} signed in from here`,
  countriesUsage: (n: number) => `usage location of ${count(n, 'user')}`,
  countriesNoSignIns: 'No sign-in record carried a location: the list below comes from usage locations only.',
  countriesNone: 'No location data at all: add the countries by hand.',
  countriesLooksRight: 'Looks right',
  addCountry: 'Add a country (two-letter code or name)…',
  countriesChosen: (n: number) => count(n, 'country', 'countries'),
  countriesExisting: (name: string) => `Matches the existing named location "${name}".`,
  countriesToCreate: 'The plan starts with a step that creates this named location.',
}

/** Fix paths for validation findings: a plan step, or the exact portal path. */
export const VALIDATION_ACTION = {
  roadmap: { label: 'See the exclusions group step in the Roadmap', href: '#/roadmap/step/s-prereq-exclusion-group' },
  drill: { label: 'Break-glass drill step in the Roadmap', href: '#/roadmap/step/s-recurring-break-glass-drill' },
  pickAnother: { label: 'Pick a different account above', href: '#/mapping' },
  policies: { label: 'Entra admin center → Protection → Conditional Access → Policies', href: 'https://entra.microsoft.com/#view/Microsoft_AAD_ConditionalAccess/ConditionalAccessBlade/~/Policies' },
  roles: { label: 'Entra admin center → Roles & admins → Global Administrator', href: 'https://entra.microsoft.com/#view/Microsoft_AAD_IAM/RolesManagementMenuBlade/~/AllRoles' },
  namedLocations: { label: 'Entra admin center → Protection → Conditional Access → Named locations', href: 'https://entra.microsoft.com/#view/Microsoft_AAD_ConditionalAccess/ConditionalAccessBlade/~/NamedLocations' },
  userMethods: (userId: string) => ({
    label: 'Entra admin center → Users → this user → Authentication methods',
    href: `https://entra.microsoft.com/#view/Microsoft_AAD_UsersAndTenants/UserProfileMenuBlade/~/AuthenticationMethods/userId/${userId}`,
  }),
  userProfile: (userId: string) => ({
    label: 'Entra admin center → Users → this user',
    href: `https://entra.microsoft.com/#view/Microsoft_AAD_UsersAndTenants/UserProfileMenuBlade/~/overview/userId/${userId}`,
  }),
  group: (groupId: string) => ({
    label: 'Entra admin center → Groups → this group → Members',
    href: `https://entra.microsoft.com/#view/Microsoft_AAD_IAM/GroupDetailsMenuBlade/~/Members/groupId/${groupId}`,
  }),
}

export const FRAMEWORK_OPTIONS =['CIS Controls v8', 'Essential Eight (ACSC)', 'NIST CSF']

export const COMMON_TIMEZONES = [
  'Australia/Sydney',
  'Australia/Brisbane',
  'Australia/Perth',
  'Pacific/Auckland',
  'Europe/London',
  'Europe/Berlin',
  'America/New_York',
  'America/Chicago',
  'America/Los_Angeles',
  'Asia/Singapore',
  'UTC',
]
