// Contrast and responsive audit (prompt 39 §7, §8; prompt 47 Part 1 item 5).
//
// Two questions no unit test can answer, because both are about what the
// browser actually computed rather than what the source says:
//
//   L5  Does every piece of text and every control edge clear the WCAG AA
//       contrast ratio, in BOTH modes, on every built surface? The lowest
//       ratio found per mode is reported, not just the failures.
//
//   L6  At 360, 700, 1024, 1440 and 1920, does every built surface reflow
//       inside the viewport, with tables scrolling in their own container?
//
// The surfaces come from docs/qa/page-contracts.json: every entry whose status
// is 'built', reached in its named mock state with its actions performed, the
// same way the UI inventory reaches it. Until a surface is built it is not
// audited; a legacy page is measured by nothing here, and dies in prompt 49.
//
// Exits non-zero on a failure, so CI can run it. Known failures are waived by
// review id, and a waiver that stops matching fails the run rather than rotting.
import { spawn, spawnSync } from 'node:child_process'
import { createServer } from 'node:http'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { extname, join, normalize } from 'node:path'

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

const PORT = Number(process.env.AUDIT_PORT ?? 5202)
const CDP_PORT = Number(process.env.AUDIT_CDP_PORT ?? 9447)
const BASE = `http://localhost:${PORT}/rollout/?dev=1&mock=1`
const CONTRACTS = JSON.parse(readFileSync(process.env.CONTRACTS_JSON ?? 'docs/qa/page-contracts.json', 'utf8'))

const WIDTHS = [360, 700, 1024, 1440, 1920]
const MODES = ['light', 'dark']

// Known failures. Each names the finding that will remove it.
const WAIVED = []

/** The built surfaces, one probe each: route, state, actions and root, as the contract reaches them. */
const SURFACES = CONTRACTS.surfaces
  .filter((s) => s.status === 'built')
  .map((s) => ({ id: s.id, route: s.reach.route, state: s.reach.state ?? 'scanned', actions: s.reach.actions ?? [], root: s.reach.root ?? 'main.page', eachTab: s.reach.eachTab === true }))

if (SURFACES.length === 0) {
  console.log('layout-audit: no built surface in the contract yet; nothing to audit.')
  mkdirSync('docs/qa', { recursive: true })
  writeFileSync('docs/qa/layout-audit.md', '# Contrast and responsive audit\n\nGenerated by `npm run layout-audit`. No built surface in the contract yet.\n')
  process.exit(0)
}

const CANDIDATES = [
  process.env.CHROME,
  'C:/Program Files/Google/Chrome/Application/chrome.exe',
  'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
  '/usr/bin/google-chrome',
  '/usr/bin/google-chrome-stable',
  '/usr/bin/chromium-browser',
  '/usr/bin/chromium',
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
].filter(Boolean)
const CHROME = CANDIDATES.find((p) => existsSync(p))
if (!CHROME) {
  console.error('layout-audit: no Chrome binary found; set CHROME=/path/to/chrome')
  process.exit(2)
}

const vite = spawn(process.execPath, ['node_modules/vite/bin/vite.js', '--port', String(PORT), '--strictPort'], {
  stdio: ['ignore', 'pipe', 'pipe'],
})
let up = false
for (let i = 0; i < 120 && !up; i++) {
  try {
    up = (await fetch(`http://localhost:${PORT}/rollout/`)).ok
  } catch {
    await sleep(200)
  }
}
if (!up) {
  console.error('layout-audit: dev server did not start')
  vite.kill()
  process.exit(2)
}

const chrome = spawn(
  CHROME,
  [
    '--headless=new', '--disable-gpu', '--no-sandbox', '--no-first-run', '--hide-scrollbars',
    `--user-data-dir=${process.env.TMPDIR ?? process.env.TEMP ?? '/tmp'}/iamai-audit-profile`,
    `--remote-debugging-port=${CDP_PORT}`, '--window-size=1440,1200', 'about:blank',
  ],
  { stdio: 'ignore' },
)
let targets = []
for (let i = 0; i < 120 && targets.length === 0; i++) {
  try {
    targets = await (await fetch(`http://localhost:${CDP_PORT}/json/list`)).json()
  } catch {
    await sleep(200)
  }
}
const page = targets.find((t) => t.type === 'page')
const ws = new WebSocket(page.webSocketDebuggerUrl)
await new Promise((r) => (ws.onopen = r))
let id = 0
const pending = new Map()
ws.onmessage = (m) => {
  const msg = JSON.parse(m.data)
  if (msg.id && pending.has(msg.id)) {
    pending.get(msg.id)(msg)
    pending.delete(msg.id)
  }
}
const send = (method, params = {}) =>
  new Promise((res) => {
    const i = ++id
    pending.set(i, res)
    ws.send(JSON.stringify({ id: i, method, params }))
  })
const evaluate = async (expr) => {
  const r = await send('Runtime.evaluate', { expression: expr, awaitPromise: true, returnByValue: true })
  if (r.result.exceptionDetails) throw new Error(r.result.exceptionDetails.exception?.description ?? 'evaluate failed')
  return r.result.result.value
}
await send('Page.enable')
await send('Runtime.enable')
console.log('layout-audit: ' + (await (await fetch(`http://localhost:${CDP_PORT}/json/version`)).json()).Browser)

const resize = (width) => send('Emulation.setDeviceMetricsOverride', { width, height: 1000, deviceScaleFactor: 1, mobile: width < 700 })
let currentMode = 'light'
const setMode = async (mode) => {
  currentMode = mode
  await evaluate(`(() => { try { localStorage.setItem('iamai-theme', ${JSON.stringify(mode)}) } catch {} })()`)
}
/** Reach a surface: its state in the URL, the mode already stored, then its actions. */
const reach = async (s) => {
  await send('Page.navigate', { url: `${BASE}&state=${encodeURIComponent(s.state)}#${s.route}` })
  await sleep(1300)
  await evaluate(`(() => { document.documentElement.dataset.theme = ${JSON.stringify(currentMode)} })()`)
  await sleep(150)
  for (const a of s.actions) {
    if (a.text !== undefined) {
      const re = new RegExp(a.text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))
      await evaluate(`(() => { const el = [...document.querySelectorAll(${JSON.stringify(a.click)})].find((x) => ${re}.test((x.textContent || '').trim())); if (el) el.click(); return !!el })()`)
    } else {
      await evaluate(`(() => { const els = [...document.querySelectorAll(${JSON.stringify(a.click)})].filter((e) => e.offsetParent !== null || e.tagName === 'SUMMARY'); const el = els[${Number(a.nth ?? 1) - 1}]; if (el) el.click(); return !!el })()`)
    }
    await sleep(500)
  }
}
const rootExpr = (root) => (root === 'visiblePanel' ? `[...document.querySelectorAll('main.page .tab-panel')].find((p) => p.offsetParent !== null)` : `document.querySelector(${JSON.stringify(root)})`)

// ---- the contrast probe, injected into the page ----
//
// Ratios come from what the browser painted, walking up for a background
// because most elements are transparent. Text under 24px (or under 18.66px
// bold) needs 4.5; larger text and control edges need 3. Besides the failures
// the probe returns the lowest ratio it saw, per kind, so the report can say how
// much headroom a mode has rather than only whether it passed.
const CONTRAST = (rootJs) => `(() => {
  const root = ${rootJs}
  if (!root) return { rows: [], lowest: null }
  const parse = (c) => {
    const m = c.match(/rgba?\\(([^)]+)\\)/)
    if (!m) return null
    const [r, g, b, a] = m[1].split(',').map((n) => parseFloat(n))
    return { r, g, b, a: a === undefined ? 1 : a }
  }
  const lum = ({ r, g, b }) => {
    const f = (v) => { const s = v / 255; return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4) }
    return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b)
  }
  const ratio = (a, b) => { const l1 = lum(a), l2 = lum(b); return (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05) }
  const bgOf = (el) => {
    for (let n = el; n; n = n.parentElement) {
      const c = parse(getComputedStyle(n).backgroundColor)
      if (c && c.a > 0.5) return c
    }
    return parse(getComputedStyle(document.body).backgroundColor) || { r: 255, g: 255, b: 255, a: 1 }
  }
  const visible = (el) => {
    const r = el.getBoundingClientRect()
    return r.width > 1 && r.height > 1 && getComputedStyle(el).visibility !== 'hidden'
  }
  const label = (el) => (el.textContent || '').trim().replace(/\\s+/g, ' ').slice(0, 48)
  const rows = []
  const seen = new Set()
  let lowest = null
  const note = (kind, got, need, detail) => {
    if (lowest === null || got < lowest.got) lowest = { kind, got: Math.round(got * 100) / 100, need, detail }
  }
  const record = (kind, el, got, need, detail) => {
    const key = kind + '|' + detail
    if (seen.has(key)) return
    seen.add(key)
    rows.push({ kind, got: Math.round(got * 100) / 100, need, detail })
  }
  for (const el of root.querySelectorAll('*')) {
    if (!visible(el) || el.closest('.devtools, .print-only')) continue
    if ([...el.children].some((c) => (c.textContent || '').trim().length > 0)) continue
    const text = label(el)
    if (!text) continue
    const cs = getComputedStyle(el)
    const fg = parse(cs.color)
    if (!fg || fg.a < 0.5) continue
    const size = parseFloat(cs.fontSize)
    // Prompt 49.1 item 14: all text below 18px needs 4.5:1 in both modes; only
    // 18px and up (headings) may sit at 3:1. The build fails under this floor.
    const need = size >= 18 ? 3 : 4.5
    const r = ratio(fg, bgOf(el))
    note('text', r, need, el.className + ' :: ' + text)
    if (r < need) record('text', el, r, need, el.className + ' :: ' + text)
  }
  for (const el of root.querySelectorAll('button, input, select, textarea, .btn')) {
    if (!visible(el)) continue
    const cs = getComputedStyle(el)
    if (parseFloat(cs.borderTopWidth) < 0.5) continue
    const edge = parse(cs.borderTopColor)
    if (!edge || edge.a < 0.5) continue
    const r = ratio(edge, bgOf(el.parentElement ?? el))
    note('control edge', r, 3, el.className || el.tagName)
    if (r < 3) record('control edge', el, r, 3, el.className || el.tagName)
  }
  // The status dot is a component: 3:1 against the page it sits on.
  for (const el of root.querySelectorAll('.status')) {
    if (!visible(el)) continue
    const dot = parse(getComputedStyle(el, '::before').backgroundColor)
    if (!dot || dot.a < 0.5) continue
    const r = ratio(dot, bgOf(el))
    note('status dot', r, 3, el.className + ' :: ' + label(el))
    if (r < 3) record('status dot', el, r, 3, el.className + ' :: ' + label(el))
  }
  return { rows, lowest }
})()`

/** Overflow and table behaviour at one width. */
const LAYOUT = `(() => {
  const de = document.documentElement
  const wide = [...document.querySelectorAll('table')]
    .filter((t) => t.getBoundingClientRect().width > 1)
    .filter((t) => {
      if (t.scrollWidth <= de.clientWidth) return false
      for (let n = t.parentElement; n && n !== document.body; n = n.parentElement) {
        const ox = getComputedStyle(n).overflowX
        if ((ox === 'auto' || ox === 'scroll') && n.clientWidth < n.scrollWidth) return false
      }
      return true
    })
    .map((t) => (t.className || 'table') + ' ' + Math.round(t.scrollWidth) + 'px')
  const scrolledBy = (el) => {
    for (let n = el.parentElement; n && n !== document.body; n = n.parentElement) {
      const ox = getComputedStyle(n).overflowX
      if (ox === 'auto' || ox === 'scroll' || ox === 'hidden') return true
    }
    return false
  }
  const offenders = [...document.querySelectorAll('body *')]
    .filter((el) => !el.closest('.devtools, .print-only'))
    .map((el) => ({ el, r: el.getBoundingClientRect() }))
    .filter((x) => Math.round(x.r.right) > de.clientWidth + 1 && !scrolledBy(x.el))
    .sort((a, b) => b.r.right - a.r.right)
    .slice(0, 8)
    .map(function (x) {
      var cls = x.el.className && typeof x.el.className === 'string' ? '.' + x.el.className.trim().split(/\\s+/).join('.') : ''
      return x.el.tagName.toLowerCase() + cls + ' right=' + Math.round(x.r.right) + ' w=' + Math.round(x.r.width)
    })
  return {
    docWidth: Math.round(de.scrollWidth),
    clientWidth: Math.round(de.clientWidth),
    offenders,
    pageOverflow: Math.max(0, Math.round(de.scrollWidth - de.clientWidth)),
    tables: wide,
  }
})()`

const findings = []
const add = (where, what) => findings.push({ where, what })
const lowestByMode = {}

// ---- L5: contrast, both modes, every built surface, every width ----
for (const mode of MODES) {
  await resize(1440)
  await send('Page.navigate', { url: `${BASE}#/connect` })
  await sleep(600)
  await setMode(mode)
  for (const width of WIDTHS) {
    await resize(width)
    for (const s of SURFACES) {
      await reach(s)
      const tabs = s.eachTab ? await evaluate(`[...document.querySelectorAll('main.page [role=tab], main.page .tab')].filter((e) => e.offsetParent !== null).length`) : 1
      for (let t = 0; t < Math.max(1, tabs); t++) {
        if (s.eachTab) {
          await evaluate(`(() => { const el = [...document.querySelectorAll('main.page [role=tab], main.page .tab')].filter((e) => e.offsetParent !== null)[${t}]; if (el) el.click() })()`)
          await sleep(350)
        }
        const out = await evaluate(CONTRAST(rootExpr(s.root)))
        for (const r of out?.rows ?? []) add(`${mode} ${width}px ${s.id}`, `${r.kind} ${r.got}:1 (needs ${r.need}) — ${r.detail}`)
        const low = out?.lowest
        if (low && (!lowestByMode[mode] || low.got < lowestByMode[mode].got)) lowestByMode[mode] = { ...low, where: `${width}px ${s.id}` }
      }
      // L6 while we are here: reflow at this width.
      const l = await evaluate(LAYOUT)
      if (l && l.pageOverflow > 2) {
        add(`${mode} ${width}px ${s.id}`, `the page scrolls sideways by ${l.pageOverflow}px (doc ${l.docWidth} vs client ${l.clientWidth})`)
        for (const o of l.offenders) add(`${mode} ${width}px ${s.id}`, `  past the edge: ${o}`)
      }
      for (const t of l?.tables ?? []) add(`${mode} ${width}px ${s.id}`, `a table overflows the page rather than its own container: ${t}`)
    }
  }
}

// ---- the home page (prompt 47.1 Part 3 item 14): both modes, five widths ----
//
// The home is assembled into dist/ by scripts/assemble-site.mjs, so it is
// served from there by a small static server; when only the planner has been
// built, the assembler is run first. Fonts come from dist/<TOOL_PATH>/fonts.
const TOOL_PATH = process.env.TOOL_PATH ?? 'rollout'
const HOME_PORT = Number(process.env.AUDIT_HOME_PORT ?? 5203)
if (!existsSync('dist/index.html') && existsSync(`dist/${TOOL_PATH}/index.html`)) spawnSync(process.execPath, ['scripts/assemble-site.mjs'], { stdio: 'inherit' })
let homeAudited = false
if (existsSync('dist/index.html')) {
  const MIME = { '.html': 'text/html; charset=utf-8', '.css': 'text/css', '.js': 'text/javascript', '.png': 'image/png', '.svg': 'image/svg+xml', '.woff2': 'font/woff2', '.json': 'application/json', '.txt': 'text/plain' }
  const server = createServer((req, res) => {
    const path = normalize(decodeURIComponent((req.url ?? '/').split('?')[0])).replace(/^(\.\.[/\\])+/, '')
    let file = join('dist', path)
    if (path.endsWith('/') || path === '\\' || path === '.') file = join('dist', path, 'index.html')
    if (!existsSync(file)) {
      res.statusCode = 404
      res.end()
      return
    }
    res.setHeader('Content-Type', MIME[extname(file)] ?? 'application/octet-stream')
    res.end(readFileSync(file))
  })
  await new Promise((r) => server.listen(HOME_PORT, r))
  const HOME = `http://localhost:${HOME_PORT}/`
  for (const mode of MODES) {
    await resize(1440)
    await send('Page.navigate', { url: HOME })
    await sleep(600)
    await setMode(mode)
    for (const width of WIDTHS) {
      await resize(width)
      await send('Page.navigate', { url: HOME })
      await sleep(700)
      await evaluate(`(() => { document.documentElement.dataset.theme = ${JSON.stringify(mode)} })()`)
      await sleep(150)
      const out = await evaluate(CONTRAST('document.body'))
      for (const r of out?.rows ?? []) add(`${mode} ${width}px home`, `${r.kind} ${r.got}:1 (needs ${r.need}) — ${r.detail}`)
      const low = out?.lowest
      if (low && (!lowestByMode[mode] || low.got < lowestByMode[mode].got)) lowestByMode[mode] = { ...low, where: `${width}px home` }
      const l = await evaluate(LAYOUT)
      if (l && l.pageOverflow > 2) {
        add(`${mode} ${width}px home`, `the page scrolls sideways by ${l.pageOverflow}px (doc ${l.docWidth} vs client ${l.clientWidth})`)
        for (const o of l.offenders) add(`${mode} ${width}px home`, `  past the edge: ${o}`)
      }
    }
  }
  server.close()
  homeAudited = true
} else {
  console.log('layout-audit: the home page is not built (dist/index.html); run npm run build:site to include it.')
}

// ---- report ----
mkdirSync('docs/qa', { recursive: true })
const unwaived = findings.filter((f) => !WAIVED.some((w) => `${f.where} ${f.what}`.includes(w.match)))
const lines = [
  '# Contrast and responsive audit',
  '',
  'Generated by `npm run layout-audit`. Contrast is computed from what the browser',
  `painted, in both modes, on every built surface (${SURFACES.length})${homeAudited ? ' and the home page' : ''}, at 360, 700, 1024, 1440 and 1920.`,
  '',
  `${findings.length} findings, ${unwaived.length} unwaived.`,
  '',
  '## Lowest ratio per mode',
  '',
  ...MODES.map((m) => {
    const l = lowestByMode[m]
    return l ? `- ${m}: ${l.got}:1 (needs ${l.need}) — ${l.kind} — ${l.detail} — at ${l.where}` : `- ${m}: nothing measured`
  }),
  '',
]
const byWhere = new Map()
for (const f of findings) byWhere.set(f.where, [...(byWhere.get(f.where) ?? []), f.what])
for (const [where, what] of byWhere) {
  lines.push(`## ${where}`, '')
  for (const w of what) lines.push(`- ${w}`)
  lines.push('')
}
writeFileSync('docs/qa/layout-audit.md', lines.join('\n'))
console.log(`layout-audit: ${SURFACES.length} built surfaces${homeAudited ? ' and the home page' : ''}; ${findings.length} findings (${unwaived.length} unwaived) -> docs/qa/layout-audit.md`)
for (const m of MODES) {
  const l = lowestByMode[m]
  console.log(`  lowest ${m}: ${l ? `${l.got}:1 (needs ${l.need}) ${l.kind} — ${l.detail} — at ${l.where}` : 'nothing measured'}`)
}
for (const f of unwaived.slice(0, 40)) console.log(`  ${f.where}: ${f.what}`)

const stale = WAIVED.filter((w) => !findings.some((f) => `${f.where} ${f.what}`.includes(w.match)))
for (const w of stale) console.error(`layout-audit: waiver ${w.id} no longer matches anything; delete it`)

ws.close()
chrome.kill()
vite.kill()
process.exit(unwaived.length > 0 || stale.length > 0 ? 1 : 0)
